// Auto-generated. New colleges not already in src/tools/schools.ts.
// Source: US Department of Education College Scorecard API.
// Refresh: re-run scripts/fetch and rebuild from /tmp/colleges_out.json filtered by schools.ts slugs.

import type { CollegeStat } from "./collegeStats";

export interface ExtraCollege {
  slug: string;
  name: string;
  shortName: string;
  location: string;
  state: string;
  type: "Public" | "Private";
  category: "Ivy League" | "Elite Private" | "Top Public" | "Liberal Arts" | "Top Tech / STEM" | "Selective Private";
  knownFor: string;
  ipedsId?: number;
}

export const extraColleges: ExtraCollege[] = [
  {
    slug: "uc-berkeley",
    name: "University of California-Berkeley",
    shortName: "UC Berkeley",
    location: "Berkeley, CA",
    state: "CA",
    type: "Public",
    category: "Top Public",
    knownFor: "the most selective UC, top-ranked engineering and computer science programs, and a tradition of free-speech activism",
    ipedsId: 110635,
  },
  {
    slug: "washington-lee",
    name: "Washington and Lee University",
    shortName: "Washington & Lee",
    location: "Lexington, VA",
    state: "VA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the Honor System, the Williams School of Commerce, and a campus in Lexington, Virginia",
    ipedsId: 234207,
  },
  {
    slug: "umich",
    name: "University of Michigan-Ann Arbor",
    shortName: "Michigan",
    location: "Ann Arbor, MI",
    state: "MI",
    type: "Public",
    category: "Top Public",
    knownFor: "Big Ten flagship in Ann Arbor, Ross School of Business, College of Engineering, and one of the largest research budgets in the U.S.",
    ipedsId: 170976,
  },
  {
    slug: "skidmore",
    name: "Skidmore College",
    shortName: "Skidmore",
    location: "Saratoga Springs, NY",
    state: "NY",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the Saratoga Springs campus, strong programs in business through the Periclean Honors Forum, and the arts",
    ipedsId: 195526,
  },
  {
    slug: "fsu",
    name: "Florida State University",
    shortName: "FSU",
    location: "Tallahassee, FL",
    state: "FL",
    type: "Public",
    category: "Top Public",
    knownFor: "a Tallahassee campus, the College of Motion Picture Arts, and strong programs in meteorology and oceanography",
    ipedsId: 134097,
  },
  {
    slug: "reed",
    name: "Reed College",
    shortName: "Reed",
    location: "Portland, OR",
    state: "OR",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the senior thesis and Hum 110, no letter grades shown to students by default, and a Portland, Oregon campus",
    ipedsId: 209922,
  },
  {
    slug: "pitzer",
    name: "Pitzer College",
    shortName: "Pitzer",
    location: "Claremont, CA",
    state: "CA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "being a Claremont Colleges member with progressive social-justice values and the open curriculum",
    ipedsId: 121257,
  },
  {
    slug: "ut-austin",
    name: "The University of Texas at Austin",
    shortName: "UT Austin",
    location: "Austin, TX",
    state: "TX",
    type: "Public",
    category: "Top Public",
    knownFor: "the McCombs School of Business, the Cockrell School of Engineering, and a flagship Texas campus next to the state capital",
    ipedsId: 228778,
  },
  {
    slug: "villanova",
    name: "Villanova University",
    shortName: "Villanova",
    location: "Villanova, PA",
    state: "PA",
    type: "Private",
    category: "Selective Private",
    knownFor: "Augustinian Catholic tradition, the Villanova School of Business, and a suburban Philadelphia campus",
    ipedsId: 216597,
  },
  {
    slug: "macalester",
    name: "Macalester College",
    shortName: "Macalester",
    location: "Saint Paul, MN",
    state: "MN",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "internationalism and global citizenship as core values, a St. Paul campus, and strong programs in economics and political science",
    ipedsId: 173902,
  },
  {
    slug: "trinity-ct",
    name: "Trinity College",
    shortName: "Trinity (CT)",
    location: "Hartford, CT",
    state: "CT",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the Hartford campus, strong programs in international studies and the Trinity-La MaMa Performing Arts Program in NYC",
    ipedsId: 130590,
  },
  {
    slug: "bryn-mawr",
    name: "Bryn Mawr College",
    shortName: "Bryn Mawr",
    location: "Bryn Mawr, PA",
    state: "PA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "being a women's college with the Bi-Co consortium with Haverford, and the Self-Government Association tradition",
    ipedsId: 211273,
  },
  {
    slug: "kenyon",
    name: "Kenyon College",
    shortName: "Kenyon",
    location: "Gambier, OH",
    state: "OH",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the Kenyon Review literary magazine, English department reputation, and a Gambier, Ohio campus",
    ipedsId: 203535,
  },
  {
    slug: "lafayette",
    name: "Lafayette College",
    shortName: "Lafayette",
    location: "Easton, PA",
    state: "PA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the rare combination of strong engineering and liberal arts on a small campus in Easton, Pennsylvania",
    ipedsId: 213385,
  },
  {
    slug: "william-mary",
    name: "William & Mary",
    shortName: "William & Mary",
    location: "Williamsburg, VA",
    state: "VA",
    type: "Public",
    category: "Top Public",
    knownFor: "the second-oldest college in the U.S., a tight liberal-arts feel for a public, and a campus in Williamsburg, Virginia",
    ipedsId: 231624,
  },
  {
    slug: "oberlin",
    name: "Oberlin College",
    shortName: "Oberlin",
    location: "Oberlin, OH",
    state: "OH",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the Oberlin Conservatory of Music alongside the College of Arts and Sciences, and a tradition of social activism in Ohio",
    ipedsId: 204501,
  },
  {
    slug: "mt-holyoke",
    name: "Mount Holyoke College",
    shortName: "Mount Holyoke",
    location: "South Hadley, MA",
    state: "MA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "being one of the original Seven Sisters women's colleges, a Five College Consortium member, and a South Hadley, MA campus",
    ipedsId: 166939,
  },
  {
    slug: "uga",
    name: "University of Georgia",
    shortName: "Georgia",
    location: "Athens, GA",
    state: "GA",
    type: "Public",
    category: "Top Public",
    knownFor: "the Terry College of Business, the Grady College of Journalism, and an Athens campus with strong SEC traditions",
    ipedsId: 139959,
  },
  {
    slug: "whitman",
    name: "Whitman College",
    shortName: "Whitman",
    location: "Walla Walla, WA",
    state: "WA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the Walla Walla, Washington campus, the encounter with the canon first-year program, and outdoor culture",
    ipedsId: 237057,
  },
  {
    slug: "scripps",
    name: "Scripps College",
    shortName: "Scripps",
    location: "Claremont, CA",
    state: "CA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the Claremont Colleges women's college, strong humanities programs, and the Core Curriculum",
    ipedsId: 123165,
  },
  {
    slug: "uw-seattle",
    name: "University of Washington-Seattle Campus",
    shortName: "UW",
    location: "Seattle, WA",
    state: "WA",
    type: "Public",
    category: "Top Public",
    knownFor: "the Paul G. Allen School of Computer Science, strong direct ties to Seattle tech, and the Foster School of Business",
    ipedsId: 236948,
  },
  {
    slug: "brandeis",
    name: "Brandeis University",
    shortName: "Brandeis",
    location: "Waltham, MA",
    state: "MA",
    type: "Private",
    category: "Selective Private",
    knownFor: "Jewish-sponsored, nonsectarian roots, strong programs in social justice and Middle Eastern studies, and a campus in Waltham, Massachusetts",
    ipedsId: 165015,
  },
  {
    slug: "illinois",
    name: "University of Illinois Urbana-Champaign",
    shortName: "Illinois",
    location: "Champaign, IL",
    state: "IL",
    type: "Public",
    category: "Top Public",
    knownFor: "the Grainger College of Engineering, top-ranked computer science and accounting programs, and a Big Ten campus in Urbana-Champaign",
    ipedsId: 145637,
  },
  {
    slug: "union",
    name: "Union College",
    shortName: "Union",
    location: "Schenectady, NY",
    state: "NY",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the trimester calendar, strong engineering for a liberal arts college, and a Schenectady campus",
    ipedsId: 196866,
  },
  {
    slug: "uw-madison",
    name: "University of Wisconsin-Madison",
    shortName: "Wisconsin",
    location: "Madison, WI",
    state: "WI",
    type: "Public",
    category: "Top Public",
    knownFor: "Big Ten research flagship, strong programs across the College of Letters and Science, and a campus on Lake Mendota",
    ipedsId: 240444,
  },
  {
    slug: "syracuse",
    name: "Syracuse University",
    shortName: "Syracuse",
    location: "Syracuse, NY",
    state: "NY",
    type: "Private",
    category: "Selective Private",
    knownFor: "the Newhouse School of Public Communications, strong sports culture, and central New York campus",
    ipedsId: 196413,
  },
  {
    slug: "george-washington",
    name: "George Washington University",
    shortName: "GW",
    location: "Washington, DC",
    state: "DC",
    type: "Private",
    category: "Selective Private",
    knownFor: "its Foggy Bottom campus blocks from the White House, strong programs in international affairs and political science, and access to D.C. internships",
    ipedsId: 131469,
  },
  {
    slug: "stevens",
    name: "Stevens Institute of Technology",
    shortName: "Stevens",
    location: "Hoboken, NJ",
    state: "NJ",
    type: "Private",
    category: "Top Tech / STEM",
    knownFor: "a Hoboken campus across the Hudson from Manhattan, and strong programs in financial engineering and quantitative finance",
    ipedsId: 186867,
  },
  {
    slug: "uconn",
    name: "University of Connecticut",
    shortName: "UConn",
    location: "Storrs, CT",
    state: "CT",
    type: "Public",
    category: "Top Public",
    knownFor: "the School of Business, strong basketball programs, and a Storrs campus",
    ipedsId: 129020,
  },
  {
    slug: "northeastern",
    name: "Northeastern University",
    shortName: "Northeastern",
    location: "Boston, MA",
    state: "MA",
    type: "Private",
    category: "Elite Private",
    knownFor: "the co-op program that integrates 6-month full-time work placements into the undergraduate degree, and a strong network in Boston tech and consulting",
  },
  {
    slug: "rice",
    name: "Rice University",
    shortName: "Rice",
    location: "Houston, TX",
    state: "TX",
    type: "Private",
    category: "Elite Private",
    knownFor: "the residential college system, a small student body for a major research university, and a culture that rewards collaboration over competition",
  },
  {
    slug: "nyu",
    name: "New York University",
    shortName: "NYU",
    location: "New York, NY",
    state: "NY",
    type: "Private",
    category: "Elite Private",
    knownFor: "its Greenwich Village campus integrated into Manhattan, the Stern, Tisch, and Gallatin schools, and global study sites in Abu Dhabi and Shanghai",
  },
  {
    slug: "usc",
    name: "University of Southern California",
    shortName: "USC",
    location: "Los Angeles, CA",
    state: "CA",
    type: "Private",
    category: "Elite Private",
    knownFor: "the cinematic arts and journalism schools, deep alumni networks in entertainment and tech, and a strong culture of school spirit and sports",
  },
  {
    slug: "emory",
    name: "Emory University",
    shortName: "Emory",
    location: "Atlanta, GA",
    state: "GA",
    type: "Private",
    category: "Elite Private",
    knownFor: "strong undergraduate health and pre-med pipeline, the Goizueta Business School, and ties to the CDC",
  },
  {
    slug: "caltech",
    name: "California Institute of Technology",
    shortName: "Caltech",
    location: "Pasadena, CA",
    state: "CA",
    type: "Private",
    category: "Top Tech / STEM",
    knownFor: "a rigorous core curriculum across all majors, the Honor Code, and a small student body in Pasadena focused on physics, engineering, and computer science",
  },
  {
    slug: "boston-college",
    name: "Boston College",
    shortName: "BC",
    location: "Chestnut Hill, MA",
    state: "MA",
    type: "Private",
    category: "Selective Private",
    knownFor: "Jesuit liberal arts tradition, the Carroll School of Management, and a campus in Chestnut Hill just outside Boston",
  },
  {
    slug: "boston-university",
    name: "Boston University",
    shortName: "BU",
    location: "Boston, MA",
    state: "MA",
    type: "Private",
    category: "Selective Private",
    knownFor: "an urban campus along Commonwealth Ave in Boston, strong programs in communication and international relations, and the College of General Studies sequence",
  },
  {
    slug: "wake-forest",
    name: "Wake Forest University",
    shortName: "Wake Forest",
    location: "Winston-Salem, NC",
    state: "NC",
    type: "Private",
    category: "Selective Private",
    knownFor: "small classes for a research university, a tight-knit campus in Winston-Salem, and the Pro Humanitate service ethos",
  },
  {
    slug: "tulane",
    name: "Tulane University of Louisiana",
    shortName: "Tulane",
    location: "New Orleans, LA",
    state: "LA",
    type: "Private",
    category: "Selective Private",
    knownFor: "its New Orleans campus, the public service requirement built into the curriculum, and strong programs in architecture and tropical medicine",
  },
  {
    slug: "lehigh",
    name: "Lehigh University",
    shortName: "Lehigh",
    location: "Bethlehem, PA",
    state: "PA",
    type: "Private",
    category: "Selective Private",
    knownFor: "engineering and business programs in Bethlehem, Pennsylvania, and the integrated business and engineering (IBE) program",
  },
  {
    slug: "miami",
    name: "University of Miami",
    shortName: "Miami",
    location: "Coral Gables, FL",
    state: "FL",
    type: "Private",
    category: "Selective Private",
    knownFor: "a Coral Gables campus near Miami, marine biology and music industry programs, and ACC athletics",
  },
  {
    slug: "ucla",
    name: "University of California-Los Angeles",
    shortName: "UCLA",
    location: "Los Angeles, CA",
    state: "CA",
    type: "Public",
    category: "Top Public",
    knownFor: "the largest applicant pool in the country, strong programs across the College of Letters and Science and the Henry Samueli School of Engineering, and a flagship UC presence in Los Angeles",
  },
  {
    slug: "uva",
    name: "University of Virginia",
    shortName: "UVA",
    location: "Charlottesville, VA",
    state: "VA",
    type: "Public",
    category: "Top Public",
    knownFor: "Thomas Jefferson's Academical Village, the McIntire School of Commerce, and a Charlottesville campus that's a UNESCO World Heritage Site",
  },
  {
    slug: "unc",
    name: "University of North Carolina at Chapel Hill",
    shortName: "UNC",
    location: "Chapel Hill, NC",
    state: "NC",
    type: "Public",
    category: "Top Public",
    knownFor: "being the oldest public university in the U.S., the Kenan-Flagler Business School, and the Carolina Way in Chapel Hill",
  },
  {
    slug: "georgia-tech",
    name: "Georgia Institute of Technology",
    shortName: "Georgia Tech",
    location: "Atlanta, GA",
    state: "GA",
    type: "Public",
    category: "Top Tech / STEM",
    knownFor: "engineering and computing programs in midtown Atlanta, the Stamps Scholarship, and one of the highest-ROI public engineering degrees in the U.S.",
  },
  {
    slug: "florida",
    name: "University of Florida",
    shortName: "Florida",
    location: "Gainesville, FL",
    state: "FL",
    type: "Public",
    category: "Top Public",
    knownFor: "SEC flagship in Gainesville, the Warrington College of Business, and one of the most efficient public research engines in the country",
  },
  {
    slug: "purdue",
    name: "Purdue University",
    shortName: "Purdue",
    location: "West Lafayette, IN",
    state: "IN",
    type: "Public",
    category: "Top Public",
    knownFor: "engineering and aviation programs in West Lafayette, the Krannert School of Management, and the Cradle of Astronauts tradition",
  },
  {
    slug: "maryland",
    name: "University of Maryland-College Park",
    shortName: "Maryland",
    location: "College Park, MD",
    state: "MD",
    type: "Public",
    category: "Top Public",
    knownFor: "Big Ten flagship in College Park near D.C., strong computer science and business programs, and the Robert H. Smith School of Business",
  },
  {
    slug: "virginia-tech",
    name: "Virginia Tech",
    shortName: "Virginia Tech",
    location: "Blacksburg, VA",
    state: "VA",
    type: "Public",
    category: "Top Public",
    knownFor: "Blacksburg engineering and architecture programs, the Hokie tradition, and the Pamplin College of Business",
  },
  {
    slug: "williams",
    name: "Williams College",
    shortName: "Williams",
    location: "Williamstown, MA",
    state: "MA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the Williams-Mystic and Williams-Exeter programs, the Oxford-style tutorial system, and a Berkshires campus in Williamstown",
  },
  {
    slug: "amherst",
    name: "Amherst College",
    shortName: "Amherst",
    location: "Amherst, MA",
    state: "MA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the open curriculum with no general education requirements, and access to the Five College Consortium",
  },
  {
    slug: "swarthmore",
    name: "Swarthmore College",
    shortName: "Swarthmore",
    location: "Swarthmore, PA",
    state: "PA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the honors program with double-credit seminars and external examiners, and a small Quaker-rooted campus outside Philadelphia",
  },
  {
    slug: "pomona",
    name: "Pomona College",
    shortName: "Pomona",
    location: "Claremont, CA",
    state: "CA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "being the founding member of the Claremont Colleges Consortium, with cross-registration across five undergraduate colleges",
  },
  {
    slug: "wellesley",
    name: "Wellesley College",
    shortName: "Wellesley",
    location: "Wellesley, MA",
    state: "MA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "being a women's college near Boston with strong programs in economics, political science, and the natural sciences, plus MIT cross-registration",
  },
  {
    slug: "middlebury",
    name: "Middlebury College",
    shortName: "Middlebury",
    location: "Middlebury, VT",
    state: "VT",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the language schools and Bread Loaf Writers' Conference, strong programs in international studies, and a Vermont campus",
  },
  {
    slug: "bowdoin",
    name: "Bowdoin College",
    shortName: "Bowdoin",
    location: "Brunswick, ME",
    state: "ME",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "no fraternities or sororities (replaced by college houses), strong programs in government and environmental studies, and a Brunswick, Maine campus",
  },
  {
    slug: "carleton",
    name: "Carleton College",
    shortName: "Carleton",
    location: "Northfield, MN",
    state: "MN",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the trimester academic calendar, strong programs in computer science and economics, and a Northfield, Minnesota campus",
  },
  {
    slug: "hamilton",
    name: "Hamilton College",
    shortName: "Hamilton",
    location: "Clinton, NY",
    state: "NY",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the open curriculum with no distribution requirements, strong writing-intensive teaching, and a Clinton, New York campus",
  },
  {
    slug: "vassar",
    name: "Vassar College",
    shortName: "Vassar",
    location: "Poughkeepsie, NY",
    state: "NY",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "originally founded as a women's college, now coed, with a strong arts and humanities reputation and a Poughkeepsie, NY campus",
  },
  {
    slug: "bates",
    name: "Bates College",
    shortName: "Bates",
    location: "Lewiston, ME",
    state: "ME",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "no Greek life, the senior thesis requirement, and a Lewiston, Maine campus near the White Mountains",
  },
  {
    slug: "colby",
    name: "Colby College",
    shortName: "Colby",
    location: "Waterville, ME",
    state: "ME",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the Colby Plan distribution requirements, January Plan term, and a Waterville, Maine campus",
  },
  {
    slug: "davidson",
    name: "Davidson College",
    shortName: "Davidson",
    location: "Davidson, NC",
    state: "NC",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the Honor Code, strong basketball history, and a Presbyterian liberal arts tradition outside Charlotte",
  },
  {
    slug: "haverford",
    name: "Haverford College",
    shortName: "Haverford",
    location: "Haverford, PA",
    state: "PA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the student-run Honor Code, the Bi-Co consortium with Bryn Mawr, and a Quaker-rooted suburban Philadelphia campus",
  },
  {
    slug: "smith",
    name: "Smith College",
    shortName: "Smith",
    location: "Northampton, MA",
    state: "MA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "being a women's college in the Five College Consortium, strong engineering for a liberal arts college, and a Northampton, Massachusetts campus",
  },
  {
    slug: "wesleyan",
    name: "Wesleyan University",
    shortName: "Wesleyan",
    location: "Middletown, CT",
    state: "CT",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the open curriculum, strong programs in film and the College of Letters interdisciplinary major, and a Middletown, Connecticut campus",
  },
  {
    slug: "barnard",
    name: "Barnard College",
    shortName: "Barnard",
    location: "New York, NY",
    state: "NY",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "being a women's liberal arts college within the Columbia University system, with full cross-registration access to Columbia courses",
  },
  {
    slug: "colgate",
    name: "Colgate University",
    shortName: "Colgate",
    location: "Hamilton, NY",
    state: "NY",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the Core Curriculum, off-campus study programs, and a Hamilton, New York campus",
  },
  {
    slug: "bucknell",
    name: "Bucknell University",
    shortName: "Bucknell",
    location: "Lewisburg, PA",
    state: "PA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "engineering and arts within a liberal arts setting, and a Lewisburg, Pennsylvania campus",
  },
  {
    slug: "grinnell",
    name: "Grinnell College",
    shortName: "Grinnell",
    location: "Grinnell, IA",
    state: "IA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the open curriculum with the first-year tutorial, mentored advanced projects, and a small Iowa campus",
  },
  {
    slug: "claremont-mckenna",
    name: "Claremont McKenna College",
    shortName: "Claremont McKenna",
    location: "Claremont, CA",
    state: "CA",
    type: "Private",
    category: "Liberal Arts",
    knownFor: "the Robert Day School of Economics and Finance, the Athenaeum speaker series, and Claremont Colleges access",
  },
  {
    slug: "harvey-mudd",
    name: "Harvey Mudd College",
    shortName: "Harvey Mudd",
    location: "Claremont, CA",
    state: "CA",
    type: "Private",
    category: "Top Tech / STEM",
    knownFor: "the Common Core in math, science, and engineering across all majors, and Claremont Colleges humanities cross-registration",
  },
  { slug: "uc-davis", name: "University of California-Davis", shortName: "UC Davis", location: "Davis, CA", state: "CA", type: "Public", category: "Top Public", knownFor: "agricultural and veterinary sciences, the Robert Mondavi Institute for Wine and Food Science, and a large research campus near Sacramento" },
  { slug: "uc-irvine", name: "University of California-Irvine", shortName: "UC Irvine", location: "Irvine, CA", state: "CA", type: "Public", category: "Top Public", knownFor: "strong programs in computer science, biological sciences, and the Paul Merage School of Business in Orange County" },
  { slug: "uc-san-diego", name: "University of California-San Diego", shortName: "UC San Diego", location: "La Jolla, CA", state: "CA", type: "Public", category: "Top Public", knownFor: "the residential college system, strong oceanography and biological sciences, and a La Jolla campus near Scripps Institution" },
  { slug: "uc-santa-barbara", name: "University of California-Santa Barbara", shortName: "UCSB", location: "Santa Barbara, CA", state: "CA", type: "Public", category: "Top Public", knownFor: "the College of Creative Studies, the Kavli Institute for Theoretical Physics, and a beachside campus in Santa Barbara" },
  { slug: "uc-santa-cruz", name: "University of California-Santa Cruz", shortName: "UC Santa Cruz", location: "Santa Cruz, CA", state: "CA", type: "Public", category: "Top Public", knownFor: "the residential college system, narrative evaluations alongside grades, and a redwood-forest campus above Monterey Bay" },
  { slug: "uc-riverside", name: "University of California-Riverside", shortName: "UC Riverside", location: "Riverside, CA", state: "CA", type: "Public", category: "Top Public", knownFor: "strong programs in entomology and citrus research, the School of Business, and an Inland Empire UC campus" },
  { slug: "cal-poly-slo", name: "California Polytechnic State University-San Luis Obispo", shortName: "Cal Poly SLO", location: "San Luis Obispo, CA", state: "CA", type: "Public", category: "Top Public", knownFor: "the 'Learn by Doing' philosophy, strong undergraduate engineering and architecture, and a central California coast campus" },
  { slug: "penn-state", name: "Pennsylvania State University", shortName: "Penn State", location: "University Park, PA", state: "PA", type: "Public", category: "Top Public", knownFor: "the Smeal College of Business, College of Engineering, Big Ten football, and the University Park flagship in central Pennsylvania" },
  { slug: "ohio-state", name: "Ohio State University", shortName: "Ohio State", location: "Columbus, OH", state: "OH", type: "Public", category: "Top Public", knownFor: "the Fisher College of Business, College of Engineering, Big Ten athletics, and a Columbus flagship that's one of the largest U.S. campuses" },
  { slug: "indiana", name: "Indiana University-Bloomington", shortName: "Indiana", location: "Bloomington, IN", state: "IN", type: "Public", category: "Top Public", knownFor: "the Kelley School of Business, the Jacobs School of Music, and a Bloomington campus with a strong Big Ten tradition" },
  { slug: "iowa", name: "University of Iowa", shortName: "Iowa", location: "Iowa City, IA", state: "IA", type: "Public", category: "Top Public", knownFor: "the Iowa Writers' Workshop, Tippie College of Business, and a Big Ten campus along the Iowa River" },
  { slug: "iowa-state", name: "Iowa State University", shortName: "Iowa State", location: "Ames, IA", state: "IA", type: "Public", category: "Top Public", knownFor: "engineering, agricultural sciences, and the Ivy College of Business in Ames" },
  { slug: "michigan-state", name: "Michigan State University", shortName: "Michigan State", location: "East Lansing, MI", state: "MI", type: "Public", category: "Top Public", knownFor: "the Eli Broad College of Business, supply chain management, and a Big Ten campus in East Lansing" },
  { slug: "minnesota", name: "University of Minnesota-Twin Cities", shortName: "Minnesota", location: "Minneapolis, MN", state: "MN", type: "Public", category: "Top Public", knownFor: "the Carlson School of Management, College of Science and Engineering, and a Twin Cities urban campus" },
  { slug: "rutgers", name: "Rutgers University-New Brunswick", shortName: "Rutgers", location: "New Brunswick, NJ", state: "NJ", type: "Public", category: "Top Public", knownFor: "the School of Arts and Sciences, Rutgers Business School, and a Big Ten flagship in central New Jersey" },
  { slug: "umass-amherst", name: "University of Massachusetts-Amherst", shortName: "UMass Amherst", location: "Amherst, MA", state: "MA", type: "Public", category: "Top Public", knownFor: "the Isenberg School of Management, College of Engineering, and the Five College Consortium in western Massachusetts" },
  { slug: "stony-brook", name: "Stony Brook University", shortName: "Stony Brook", location: "Stony Brook, NY", state: "NY", type: "Public", category: "Top Public", knownFor: "computer science and applied mathematics, ties to Brookhaven National Laboratory, and a SUNY flagship on Long Island" },
  { slug: "binghamton", name: "Binghamton University", shortName: "Binghamton", location: "Binghamton, NY", state: "NY", type: "Public", category: "Top Public", knownFor: "the School of Management, the Watson College of Engineering, and one of the most selective SUNY campuses" },
  { slug: "buffalo", name: "University at Buffalo", shortName: "Buffalo", location: "Buffalo, NY", state: "NY", type: "Public", category: "Top Public", knownFor: "the largest SUNY campus, strong programs in management and engineering, and a Buffalo metro location" },
  { slug: "georgia-state", name: "Georgia State University", shortName: "Georgia State", location: "Atlanta, GA", state: "GA", type: "Public", category: "Top Public", knownFor: "the Robinson College of Business, an urban Atlanta campus, and a strong record on student success and access" },
  { slug: "ut-dallas", name: "University of Texas at Dallas", shortName: "UT Dallas", location: "Richardson, TX", state: "TX", type: "Public", category: "Top Public", knownFor: "the Naveen Jindal School of Management, computer science and engineering, and a Richardson campus in the DFW metroplex" },
  { slug: "texas-am", name: "Texas A&M University", shortName: "Texas A&M", location: "College Station, TX", state: "TX", type: "Public", category: "Top Public", knownFor: "engineering, the Mays Business School, the Corps of Cadets, and an Aggie tradition in College Station" },
  { slug: "alabama", name: "University of Alabama", shortName: "Alabama", location: "Tuscaloosa, AL", state: "AL", type: "Public", category: "Top Public", knownFor: "the Culverhouse College of Business, generous merit scholarships, SEC football, and a Tuscaloosa campus" },
  { slug: "auburn", name: "Auburn University", shortName: "Auburn", location: "Auburn, AL", state: "AL", type: "Public", category: "Top Public", knownFor: "the Harbert College of Business, engineering, and an SEC tradition in eastern Alabama" },
  { slug: "tennessee", name: "University of Tennessee-Knoxville", shortName: "Tennessee", location: "Knoxville, TN", state: "TN", type: "Public", category: "Top Public", knownFor: "the Haslam College of Business, Tickle College of Engineering, and the SEC flagship in Knoxville" },
  { slug: "south-carolina", name: "University of South Carolina-Columbia", shortName: "South Carolina", location: "Columbia, SC", state: "SC", type: "Public", category: "Top Public", knownFor: "the Darla Moore School of Business' international business program, and the SEC flagship in Columbia" },
  { slug: "kentucky", name: "University of Kentucky", shortName: "Kentucky", location: "Lexington, KY", state: "KY", type: "Public", category: "Top Public", knownFor: "the Gatton College of Business and Economics, the College of Engineering, and an SEC flagship in Lexington" },
  { slug: "lsu", name: "Louisiana State University", shortName: "LSU", location: "Baton Rouge, LA", state: "LA", type: "Public", category: "Top Public", knownFor: "the E.J. Ourso College of Business, petroleum engineering, and the SEC flagship in Baton Rouge" },
  { slug: "ole-miss", name: "University of Mississippi", shortName: "Ole Miss", location: "University, MS", state: "MS", type: "Public", category: "Top Public", knownFor: "the School of Business Administration, the Lott Leadership Institute, and an SEC flagship in Oxford, Mississippi" },
  { slug: "arkansas", name: "University of Arkansas", shortName: "Arkansas", location: "Fayetteville, AR", state: "AR", type: "Public", category: "Top Public", knownFor: "the Sam M. Walton College of Business, supply chain and retail programs, and an SEC flagship in Fayetteville" },
  { slug: "missouri", name: "University of Missouri", shortName: "Missouri", location: "Columbia, MO", state: "MO", type: "Public", category: "Top Public", knownFor: "the Missouri School of Journalism, the Trulaske College of Business, and the SEC flagship in Columbia" },
  { slug: "kansas", name: "University of Kansas", shortName: "Kansas", location: "Lawrence, KS", state: "KS", type: "Public", category: "Top Public", knownFor: "the School of Business, journalism, basketball tradition, and a Big 12 flagship in Lawrence" },
  { slug: "kansas-state", name: "Kansas State University", shortName: "Kansas State", location: "Manhattan, KS", state: "KS", type: "Public", category: "Top Public", knownFor: "agriculture, engineering, and an inviting Big 12 campus in Manhattan, Kansas" },
  { slug: "nebraska", name: "University of Nebraska-Lincoln", shortName: "Nebraska", location: "Lincoln, NE", state: "NE", type: "Public", category: "Top Public", knownFor: "the College of Business, engineering, and Big Ten athletics in Lincoln" },
  { slug: "oklahoma", name: "University of Oklahoma", shortName: "Oklahoma", location: "Norman, OK", state: "OK", type: "Public", category: "Top Public", knownFor: "the Price College of Business, meteorology, and an SEC flagship in Norman" },
  { slug: "oklahoma-state", name: "Oklahoma State University", shortName: "Oklahoma State", location: "Stillwater, OK", state: "OK", type: "Public", category: "Top Public", knownFor: "the Spears School of Business, College of Engineering, and a Big 12 campus in Stillwater" },
  { slug: "colorado-boulder", name: "University of Colorado Boulder", shortName: "CU Boulder", location: "Boulder, CO", state: "CO", type: "Public", category: "Top Public", knownFor: "the Leeds School of Business, aerospace engineering, environmental sciences, and a Front Range campus in Boulder" },
  { slug: "colorado-state", name: "Colorado State University", shortName: "Colorado State", location: "Fort Collins, CO", state: "CO", type: "Public", category: "Top Public", knownFor: "the College of Veterinary Medicine, atmospheric sciences, and a Fort Collins campus near the Rockies" },
  { slug: "arizona", name: "University of Arizona", shortName: "Arizona", location: "Tucson, AZ", state: "AZ", type: "Public", category: "Top Public", knownFor: "the Eller College of Management, optical sciences, and a Pac-12 / Big 12 flagship in Tucson" },
  { slug: "arizona-state", name: "Arizona State University", shortName: "Arizona State", location: "Tempe, AZ", state: "AZ", type: "Public", category: "Top Public", knownFor: "the W. P. Carey School of Business, the Walter Cronkite School of Journalism, and an innovation-driven Tempe campus" },
  { slug: "utah", name: "University of Utah", shortName: "Utah", location: "Salt Lake City, UT", state: "UT", type: "Public", category: "Top Public", knownFor: "the David Eccles School of Business, computer science, and a Salt Lake City flagship next to the Wasatch Range" },
  { slug: "oregon", name: "University of Oregon", shortName: "Oregon", location: "Eugene, OR", state: "OR", type: "Public", category: "Top Public", knownFor: "the Lundquist College of Business, the School of Journalism and Communication, and an Eugene campus" },
  { slug: "oregon-state", name: "Oregon State University", shortName: "Oregon State", location: "Corvallis, OR", state: "OR", type: "Public", category: "Top Public", knownFor: "the College of Engineering, oceanography, and a Corvallis campus in Oregon's Willamette Valley" },
  { slug: "washington-state", name: "Washington State University", shortName: "Washington State", location: "Pullman, WA", state: "WA", type: "Public", category: "Top Public", knownFor: "the Carson College of Business, agricultural sciences, and a Pullman campus in eastern Washington" },
  { slug: "umass-lowell", name: "University of Massachusetts-Lowell", shortName: "UMass Lowell", location: "Lowell, MA", state: "MA", type: "Public", category: "Top Public", knownFor: "engineering and computer science programs, the Manning School of Business, and a Lowell campus near Boston" },
  { slug: "umass-boston", name: "University of Massachusetts-Boston", shortName: "UMass Boston", location: "Boston, MA", state: "MA", type: "Public", category: "Top Public", knownFor: "an urban Boston harbor campus, strong nursing and management programs, and a focus on first-generation student success" },
  { slug: "northern-illinois", name: "Northern Illinois University", shortName: "Northern Illinois", location: "DeKalb, IL", state: "IL", type: "Public", category: "Top Public", knownFor: "the College of Business, accounting, and a DeKalb campus in northern Illinois" },
  { slug: "drexel", name: "Drexel University", shortName: "Drexel", location: "Philadelphia, PA", state: "PA", type: "Private", category: "Selective Private", knownFor: "the cooperative education program with multiple six-month industry placements, and an urban Philadelphia campus near Penn" },
  { slug: "fordham", name: "Fordham University", shortName: "Fordham", location: "Bronx, NY", state: "NY", type: "Private", category: "Selective Private", knownFor: "Jesuit liberal arts tradition, the Gabelli School of Business at the Lincoln Center campus, and Bronx and Manhattan campuses" },
  { slug: "rensselaer", name: "Rensselaer Polytechnic Institute", shortName: "RPI", location: "Troy, NY", state: "NY", type: "Private", category: "Top Tech / STEM", knownFor: "the oldest tech school in the English-speaking world, strong engineering and computer science, and a Troy, NY campus" },
  { slug: "rit", name: "Rochester Institute of Technology", shortName: "RIT", location: "Rochester, NY", state: "NY", type: "Private", category: "Top Tech / STEM", knownFor: "the Saunders College of Business, computing security, the National Technical Institute for the Deaf, and a co-op model" },
  { slug: "wpi", name: "Worcester Polytechnic Institute", shortName: "WPI", location: "Worcester, MA", state: "MA", type: "Private", category: "Top Tech / STEM", knownFor: "the project-based curriculum with major qualifying and interactive qualifying projects, and an engineering campus in Worcester" },
  { slug: "case-western", name: "Case Western Reserve University", shortName: "Case Western", location: "Cleveland, OH", state: "OH", type: "Private", category: "Selective Private", knownFor: "the Weatherhead School of Management, strong engineering and pre-med programs, and a University Circle campus in Cleveland" },
  { slug: "rochester", name: "University of Rochester", shortName: "Rochester", location: "Rochester, NY", state: "NY", type: "Private", category: "Selective Private", knownFor: "the open curriculum across clusters, the Eastman School of Music, the Simon Business School, and a Rochester, NY campus" },
  { slug: "babson", name: "Babson College", shortName: "Babson", location: "Wellesley, MA", state: "MA", type: "Private", category: "Selective Private", knownFor: "consistently ranked No. 1 in entrepreneurship, the integrated business curriculum from year one, and a Wellesley, MA campus" },
  { slug: "bentley", name: "Bentley University", shortName: "Bentley", location: "Waltham, MA", state: "MA", type: "Private", category: "Selective Private", knownFor: "a business-focused curriculum with arts and sciences integration, and a Waltham campus near Boston" },
  { slug: "embry-riddle", name: "Embry-Riddle Aeronautical University", shortName: "Embry-Riddle", location: "Daytona Beach, FL", state: "FL", type: "Private", category: "Top Tech / STEM", knownFor: "aviation, aerospace engineering, and the Daytona Beach and Prescott campuses" },
  { slug: "smu", name: "Southern Methodist University", shortName: "SMU", location: "Dallas, TX", state: "TX", type: "Private", category: "Selective Private", knownFor: "the Cox School of Business, the Meadows School of the Arts, and a University Park campus in Dallas" },
  { slug: "tcu", name: "Texas Christian University", shortName: "TCU", location: "Fort Worth, TX", state: "TX", type: "Private", category: "Selective Private", knownFor: "the Neeley School of Business, the John V. Roach Honors College, and a Fort Worth campus" },
  { slug: "baylor", name: "Baylor University", shortName: "Baylor", location: "Waco, TX", state: "TX", type: "Private", category: "Selective Private", knownFor: "the Hankamer School of Business, the medical and pre-health pipeline, and a Big 12 campus in Waco" },
  { slug: "pepperdine", name: "Pepperdine University", shortName: "Pepperdine", location: "Malibu, CA", state: "CA", type: "Private", category: "Selective Private", knownFor: "the Graziadio Business School, international study programs, and a Malibu campus overlooking the Pacific" },
  { slug: "santa-clara", name: "Santa Clara University", shortName: "Santa Clara", location: "Santa Clara, CA", state: "CA", type: "Private", category: "Selective Private", knownFor: "the Leavey School of Business, Silicon Valley networks, and a Jesuit campus in Santa Clara" },
  { slug: "loyola-marymount", name: "Loyola Marymount University", shortName: "LMU", location: "Los Angeles, CA", state: "CA", type: "Private", category: "Selective Private", knownFor: "the College of Business Administration, the School of Film and Television, and a Westside Los Angeles campus" },
  { slug: "marquette", name: "Marquette University", shortName: "Marquette", location: "Milwaukee, WI", state: "WI", type: "Private", category: "Selective Private", knownFor: "the College of Business Administration, biomedical engineering, and a Jesuit Milwaukee campus" },
  { slug: "loyola-chicago", name: "Loyola University Chicago", shortName: "Loyola Chicago", location: "Chicago, IL", state: "IL", type: "Private", category: "Selective Private", knownFor: "the Quinlan School of Business, nursing, and Lake Shore and Water Tower campuses in Chicago" },
  { slug: "depaul", name: "DePaul University", shortName: "DePaul", location: "Chicago, IL", state: "IL", type: "Private", category: "Selective Private", knownFor: "the Driehaus College of Business, the Theatre School, and Lincoln Park and Loop campuses in Chicago" },
  { slug: "chapman", name: "Chapman University", shortName: "Chapman", location: "Orange, CA", state: "CA", type: "Private", category: "Selective Private", knownFor: "the Dodge College of Film and Media Arts, the Argyros School of Business, and an Orange County campus" },
  { slug: "elon", name: "Elon University", shortName: "Elon", location: "Elon, NC", state: "NC", type: "Private", category: "Selective Private", knownFor: "experiential learning, the Martha and Spencer Love School of Business, and a North Carolina campus" },
  { slug: "occidental", name: "Occidental College", shortName: "Occidental", location: "Los Angeles, CA", state: "CA", type: "Private", category: "Liberal Arts", knownFor: "an L.A. liberal arts college with strong programs in international relations and the United Nations program" },
  { slug: "lewis-clark", name: "Lewis & Clark College", shortName: "Lewis & Clark", location: "Portland, OR", state: "OR", type: "Private", category: "Liberal Arts", knownFor: "international affairs, environmental studies, and a Portland campus overlooking the Willamette" },
  { slug: "willamette", name: "Willamette University", shortName: "Willamette", location: "Salem, OR", state: "OR", type: "Private", category: "Liberal Arts", knownFor: "being the oldest college in the West, strong politics and economics programs, and a Salem, Oregon campus" },
  { slug: "stetson", name: "Stetson University", shortName: "Stetson", location: "DeLand, FL", state: "FL", type: "Private", category: "Liberal Arts", knownFor: "the School of Business Administration, music, and a DeLand, Florida campus" },
  { slug: "rollins", name: "Rollins College", shortName: "Rollins", location: "Winter Park, FL", state: "FL", type: "Private", category: "Liberal Arts", knownFor: "the Crummer Graduate School of Business, international relations, and a Winter Park, Florida campus" },
  { slug: "hofstra", name: "Hofstra University", shortName: "Hofstra", location: "Hempstead, NY", state: "NY", type: "Private", category: "Selective Private", knownFor: "the Frank G. Zarb School of Business, communications, and a Long Island campus" },
  { slug: "yeshiva", name: "Yeshiva University", shortName: "Yeshiva", location: "New York, NY", state: "NY", type: "Private", category: "Selective Private", knownFor: "the Sy Syms School of Business and an integrated Jewish studies and liberal arts curriculum in Manhattan" },
  { slug: "njit", name: "New Jersey Institute of Technology", shortName: "NJIT", location: "Newark, NJ", state: "NJ", type: "Public", category: "Top Tech / STEM", knownFor: "the Newark College of Engineering, Ying Wu College of Computing, and a Newark campus" },
  { slug: "cooper-union", name: "The Cooper Union for the Advancement of Science and Art", shortName: "Cooper Union", location: "New York, NY", state: "NY", type: "Private", category: "Top Tech / STEM", knownFor: "selective programs in architecture, art, and engineering and a small Manhattan campus" },
  { slug: "olin", name: "Franklin W. Olin College of Engineering", shortName: "Olin", location: "Needham, MA", state: "MA", type: "Private", category: "Top Tech / STEM", knownFor: "a project-based engineering curriculum, small class sizes, and a Needham, MA campus across from Babson" },
];

export const extraStats: Record<string, Pick<CollegeStat, "acceptanceRate" | "acceptanceRateLabel" | "sat" | "act" | "coa" | "undergradEnrollment" | "testPolicy">> = {
  "caltech": {
    acceptanceRate: 0.0257,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    coa: 86886,
    undergradEnrollment: 987,
    testPolicy: "optional",
  },
  "northeastern": {
    acceptanceRate: 0.0522,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1440, p75: 1540 },
    act: { p25: 33, p75: 35 },
    coa: 84641,
    undergradEnrollment: 17326,
    testPolicy: "optional",
  },
  "pomona": {
    acceptanceRate: 0.0709,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1490, p75: 1560 },
    act: { p25: 33, p75: 35 },
    coa: 85300,
    undergradEnrollment: 1666,
    testPolicy: "optional",
  },
  "colby": {
    acceptanceRate: 0.0709,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1460, p75: 1550 },
    act: { p25: 32, p75: 34 },
    coa: 85420,
    undergradEnrollment: 2407,
    testPolicy: "optional",
  },
  "bowdoin": {
    acceptanceRate: 0.0713,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1470, p75: 1550 },
    act: { p25: 33, p75: 35 },
    coa: 85100,
    undergradEnrollment: 1873,
    testPolicy: "optional",
  },
  "swarthmore": {
    acceptanceRate: 0.0746,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1490, p75: 1560 },
    act: { p25: 33, p75: 35 },
    coa: 84103,
    undergradEnrollment: 1613,
    testPolicy: "optional",
  },
  "rice": {
    acceptanceRate: 0.08,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1510, p75: 1570 },
    act: { p25: 34, p75: 35 },
    coa: 79788,
    undergradEnrollment: 4776,
    testPolicy: "optional",
  },
  "williams": {
    acceptanceRate: 0.0825,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1490, p75: 1570 },
    act: { p25: 34, p75: 35 },
    coa: 84860,
    undergradEnrollment: 2076,
    testPolicy: "optional",
  },
  "barnard": {
    acceptanceRate: 0.0884,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1470, p75: 1560 },
    act: { p25: 32, p75: 34 },
    coa: 89538,
    undergradEnrollment: 3264,
    testPolicy: "optional",
  },
  "ucla": {
    acceptanceRate: 0.0897,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    coa: 38614,
    undergradEnrollment: 33475,
    testPolicy: "optional",
  },
  "amherst": {
    acceptanceRate: 0.0901,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1490, p75: 1580 },
    act: { p25: 33, p75: 35 },
    coa: 87640,
    undergradEnrollment: 1911,
    testPolicy: "optional",
  },
  "nyu": {
    acceptanceRate: 0.0923,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1480, p75: 1560 },
    act: { p25: 34, p75: 35 },
    coa: 84374,
    undergradEnrollment: 28663,
    testPolicy: "optional",
  },
  "claremont-mckenna": {
    acceptanceRate: 0.0959,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1470, p75: 1560 },
    act: { p25: 33, p75: 35 },
    coa: 86500,
    undergradEnrollment: 1388,
    testPolicy: "optional",
  },
  "usc": {
    acceptanceRate: 0.0981,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1450, p75: 1550 },
    act: { p25: 32, p75: 35 },
    coa: 90300,
    undergradEnrollment: 20443,
    testPolicy: "optional",
  },
  "emory": {
    acceptanceRate: 0.1065,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1470, p75: 1550 },
    act: { p25: 32, p75: 35 },
    coa: 83622,
    undergradEnrollment: 7298,
    testPolicy: "optional",
  },
  "middlebury": {
    acceptanceRate: 0.1075,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1445, p75: 1550 },
    act: { p25: 33, p75: 35 },
    coa: 85880,
    undergradEnrollment: 2738,
    testPolicy: "optional",
  },
  "uc-berkeley": {
    acceptanceRate: 0.1098,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    coa: 45619,
    undergradEnrollment: 33068,
    testPolicy: "optional",
  },
  "boston-university": {
    acceptanceRate: 0.1111,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1420, p75: 1530 },
    act: { p25: 32, p75: 34 },
    coa: 86285,
    undergradEnrollment: 18248,
    testPolicy: "optional",
  },
  "haverford": {
    acceptanceRate: 0.1237,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1460, p75: 1550 },
    act: { p25: 33, p75: 35 },
    coa: 90382,
    undergradEnrollment: 1430,
    testPolicy: "optional",
  },
  "harvey-mudd": {
    acceptanceRate: 0.1266,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1500, p75: 1570 },
    act: { p25: 34, p75: 36 },
    coa: 90165,
    undergradEnrollment: 921,
    testPolicy: "optional",
  },
  "bates": {
    acceptanceRate: 0.1332,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1420, p75: 1530 },
    act: { p25: 31, p75: 34 },
    coa: 83532,
    undergradEnrollment: 1760,
    testPolicy: "optional",
  },
  "davidson": {
    acceptanceRate: 0.1337,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1400, p75: 1530 },
    act: { p25: 31, p75: 34 },
    coa: 79475,
    undergradEnrollment: 1867,
    testPolicy: "optional",
  },
  "hamilton": {
    acceptanceRate: 0.1362,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1450, p75: 1550 },
    act: { p25: 33, p75: 35 },
    coa: 84230,
    undergradEnrollment: 2030,
    testPolicy: "optional",
  },
  "colgate": {
    acceptanceRate: 0.1388,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1430, p75: 1540 },
    act: { p25: 33, p75: 34 },
    coa: 87070,
    undergradEnrollment: 3180,
    testPolicy: "optional",
  },
  "washington-lee": {
    acceptanceRate: 0.1397,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1430, p75: 1540 },
    act: { p25: 33, p75: 34 },
    coa: 87000,
    undergradEnrollment: 1881,
    testPolicy: "optional",
  },
  "tulane": {
    acceptanceRate: 0.1398,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1400, p75: 1520 },
    act: { p25: 31, p75: 34 },
    coa: 87004,
    undergradEnrollment: 7767,
    testPolicy: "optional",
  },
  "wellesley": {
    acceptanceRate: 0.1405,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1460, p75: 1560 },
    act: { p25: 33, p75: 35 },
    coa: 86290,
    undergradEnrollment: 2300,
    testPolicy: "optional",
  },
  "georgia-tech": {
    acceptanceRate: 0.1407,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1370, p75: 1540 },
    act: { p25: 30, p75: 34 },
    coa: 28167,
    undergradEnrollment: 18785,
    testPolicy: "optional",
  },
  "grinnell": {
    acceptanceRate: 0.1451,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1410, p75: 1540 },
    act: { p25: 31, p75: 34 },
    coa: 83440,
    undergradEnrollment: 1729,
    testPolicy: "optional",
  },
  "unc": {
    acceptanceRate: 0.1534,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1390, p75: 1530 },
    act: { p25: 28, p75: 34 },
    coa: 26055,
    undergradEnrollment: 20752,
    testPolicy: "optional",
  },
  "umich": {
    acceptanceRate: 0.1564,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1360, p75: 1530 },
    act: { p25: 31, p75: 34 },
    coa: 34654,
    undergradEnrollment: 34177,
    testPolicy: "optional",
  },
  "boston-college": {
    acceptanceRate: 0.1643,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1440, p75: 1540 },
    act: { p25: 33, p75: 35 },
    coa: 89493,
    undergradEnrollment: 10085,
    testPolicy: "optional",
  },
  "wesleyan": {
    acceptanceRate: 0.1649,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1415, p75: 1540 },
    act: { p25: 33, p75: 35 },
    coa: 89020,
    undergradEnrollment: 3067,
    testPolicy: "optional",
  },
  "uva": {
    acceptanceRate: 0.1681,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1410, p75: 1540 },
    act: { p25: 32, p75: 35 },
    coa: 39926,
    undergradEnrollment: 17597,
    testPolicy: "optional",
  },
  "vassar": {
    acceptanceRate: 0.1857,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1450, p75: 1550 },
    act: { p25: 33, p75: 35 },
    coa: 87419,
    undergradEnrollment: 2444,
    testPolicy: "optional",
  },
  "miami": {
    acceptanceRate: 0.189,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1320, p75: 1480 },
    act: { p25: 30, p75: 33 },
    coa: 86078,
    undergradEnrollment: 12913,
    testPolicy: "optional",
  },
  "carleton": {
    acceptanceRate: 0.2041,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1450, p75: 1560 },
    act: { p25: 32, p75: 34 },
    coa: 84893,
    undergradEnrollment: 2086,
    testPolicy: "optional",
  },
  "smith": {
    acceptanceRate: 0.21,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1420, p75: 1540 },
    act: { p25: 32, p75: 35 },
    coa: 86030,
    undergradEnrollment: 2544,
    testPolicy: "optional",
  },
  "skidmore": {
    acceptanceRate: 0.2105,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1340, p75: 1480 },
    act: { p25: 31, p75: 33 },
    coa: 85270,
    undergradEnrollment: 2694,
    testPolicy: "optional",
  },
  "wake-forest": {
    acceptanceRate: 0.2167,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1410, p75: 1520 },
    act: { p25: 32, p75: 34 },
    coa: 87499,
    undergradEnrollment: 5485,
    testPolicy: "optional",
  },
  "florida": {
    acceptanceRate: 0.242,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1320, p75: 1480 },
    act: { p25: 29, p75: 33 },
    coa: 22523,
    undergradEnrollment: 35629,
    testPolicy: "optional",
  },
  "fsu": {
    acceptanceRate: 0.2422,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1270, p75: 1410 },
    act: { p25: 29, p75: 32 },
    coa: 25720,
    undergradEnrollment: 32212,
    testPolicy: "optional",
  },
  "reed": {
    acceptanceRate: 0.2461,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1290, p75: 1520 },
    act: { p25: 30, p75: 34 },
    coa: 86376,
    undergradEnrollment: 1320,
    testPolicy: "optional",
  },
  "pitzer": {
    acceptanceRate: 0.2516,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    coa: 86466,
    undergradEnrollment: 1227,
    testPolicy: "optional",
  },
  "lehigh": {
    acceptanceRate: 0.2593,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1370, p75: 1500 },
    act: { p25: 31, p75: 34 },
    coa: 80856,
    undergradEnrollment: 5898,
    testPolicy: "optional",
  },
  "ut-austin": {
    acceptanceRate: 0.2664,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1250, p75: 1510 },
    act: { p25: 27, p75: 33 },
    coa: 31247,
    undergradEnrollment: 42855,
    testPolicy: "optional",
  },
  "villanova": {
    acceptanceRate: 0.2698,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1395, p75: 1510 },
    act: { p25: 32, p75: 34 },
    coa: 84793,
    undergradEnrollment: 6938,
    testPolicy: "optional",
  },
  "macalester": {
    acceptanceRate: 0.2852,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1350, p75: 1510 },
    act: { p25: 30, p75: 34 },
    coa: 82991,
    undergradEnrollment: 2131,
    testPolicy: "optional",
  },
  "bucknell": {
    acceptanceRate: 0.2893,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1310, p75: 1470 },
    act: { p25: 30, p75: 33 },
    coa: 83756,
    undergradEnrollment: 3876,
    testPolicy: "optional",
  },
  "trinity-ct": {
    acceptanceRate: 0.2925,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1298, p75: 1470 },
    act: { p25: 30, p75: 34 },
    coa: 87840,
    undergradEnrollment: 2146,
    testPolicy: "optional",
  },
  "bryn-mawr": {
    acceptanceRate: 0.2943,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1280, p75: 1510 },
    act: { p25: 29, p75: 33 },
    coa: 83250,
    undergradEnrollment: 1359,
    testPolicy: "optional",
  },
  "kenyon": {
    acceptanceRate: 0.3103,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1358, p75: 1503 },
    act: { p25: 31, p75: 33 },
    coa: 87590,
    undergradEnrollment: 1732,
    testPolicy: "optional",
  },
  "lafayette": {
    acceptanceRate: 0.3145,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1350, p75: 1500 },
    act: { p25: 31, p75: 33 },
    coa: 83133,
    undergradEnrollment: 2757,
    testPolicy: "optional",
  },
  "william-mary": {
    acceptanceRate: 0.3407,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1400, p75: 1530 },
    act: { p25: 32, p75: 34 },
    coa: 43035,
    undergradEnrollment: 7055,
    testPolicy: "optional",
  },
  "oberlin": {
    acceptanceRate: 0.3418,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1360, p75: 1520 },
    act: { p25: 31, p75: 34 },
    coa: 87404,
    undergradEnrollment: 2887,
    testPolicy: "optional",
  },
  "mt-holyoke": {
    acceptanceRate: 0.3603,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1380, p75: 1530 },
    act: { p25: 32, p75: 35 },
    coa: 84926,
    undergradEnrollment: 2169,
    testPolicy: "optional",
  },
  "uga": {
    acceptanceRate: 0.377,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1270, p75: 1480 },
    act: { p25: 29, p75: 34 },
    coa: 27993,
    undergradEnrollment: 32137,
    testPolicy: "optional",
  },
  "whitman": {
    acceptanceRate: 0.3815,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1310, p75: 1480 },
    act: { p25: 29, p75: 33 },
    coa: 78092,
    undergradEnrollment: 1531,
    testPolicy: "optional",
  },
  "scripps": {
    acceptanceRate: 0.3829,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1440, p75: 1540 },
    act: { p25: 31, p75: 34 },
    coa: 87564,
    undergradEnrollment: 1113,
    testPolicy: "optional",
  },
  "uw-seattle": {
    acceptanceRate: 0.3915,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    coa: 32446,
    undergradEnrollment: 31942,
    testPolicy: "optional",
  },
  "brandeis": {
    acceptanceRate: 0.405,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1390, p75: 1520 },
    act: { p25: 31, p75: 34 },
    coa: 86448,
    undergradEnrollment: 3618,
    testPolicy: "optional",
  },
  "illinois": {
    acceptanceRate: 0.4237,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1310, p75: 1520 },
    act: { p25: 30, p75: 34 },
    coa: 33642,
    undergradEnrollment: 36258,
    testPolicy: "optional",
  },
  "union": {
    acceptanceRate: 0.4392,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1310, p75: 1480 },
    act: { p25: 29, p75: 33 },
    coa: 84561,
    undergradEnrollment: 2046,
    testPolicy: "optional",
  },
  "maryland": {
    acceptanceRate: 0.4479,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1400, p75: 1530 },
    act: { p25: 32, p75: 35 },
    coa: 29299,
    undergradEnrollment: 30760,
    testPolicy: "optional",
  },
  "uw-madison": {
    acceptanceRate: 0.452,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1380, p75: 1520 },
    act: { p25: 29, p75: 33 },
    coa: 28679,
    undergradEnrollment: 36902,
    testPolicy: "optional",
  },
  "syracuse": {
    acceptanceRate: 0.4592,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1270, p75: 1440 },
    act: { p25: 29, p75: 32 },
    coa: 84517,
    undergradEnrollment: 15477,
    testPolicy: "optional",
  },
  "george-washington": {
    acceptanceRate: 0.4709,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1350, p75: 1500 },
    act: { p25: 31, p75: 34 },
    coa: 83856,
    undergradEnrollment: 11182,
    testPolicy: "optional",
  },
  "stevens": {
    acceptanceRate: 0.4758,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1380, p75: 1505 },
    act: { p25: 31, p75: 34 },
    coa: 79790,
    undergradEnrollment: 4222,
    testPolicy: "optional",
  },
  "purdue": {
    acceptanceRate: 0.4987,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1200, p75: 1480 },
    act: { p25: 27, p75: 34 },
    coa: 24591,
    undergradEnrollment: 44503,
    testPolicy: "optional",
  },
  "uconn": {
    acceptanceRate: 0.5239,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1210, p75: 1440 },
    act: { p25: 28, p75: 33 },
    coa: 39426,
    undergradEnrollment: 19835,
    testPolicy: "optional",
  },
  "virginia-tech": {
    acceptanceRate: 0.5478,
    acceptanceRateLabel: "Latest reported (College Scorecard)",
    sat: { p25: 1280, p75: 1450 },
    act: { p25: 28, p75: 32 },
    coa: 36951,
    undergradEnrollment: 30923,
    testPolicy: "optional",
  },
};
