export interface EssayType {
  slug: string;
  shortName: string;
  displayName: string;
  description: string;
  contextForAi: string;
  typicalWordLimit: string;
  seoKeywords: string[];
}

export const essayTypes: EssayType[] = [
  {
    slug: "personal-statement",
    shortName: "Personal Statement",
    displayName: "Personal Statement Scorer",
    description: "The 650-word Common App personal statement, usually the backbone of a US college application.",
    contextForAi: "This is a Common App personal statement (up to 650 words). Grade specifically for: whether the essay reveals character and values, whether it shows growth or reflection, whether the voice is distinct, and whether concrete scene details replace telling.",
    typicalWordLimit: "up to 650 words",
    seoKeywords: ["personal statement scorer", "common app personal statement review", "college essay rater"],
  },
  {
    slug: "why-us",
    shortName: "Why Us",
    displayName: "Why Us Essay Scorer",
    description: "The school-specific supplemental that asks why this college. Usually 100 to 400 words.",
    contextForAi: "This is a Why This College supplemental. Grade specifically for: specificity to the named school (professors, courses, programs, campus culture), whether fit feels earned not researched, and whether the student shows something concrete they would contribute.",
    typicalWordLimit: "100 to 400 words",
    seoKeywords: ["why us essay scorer", "why this college essay review", "why school essay grader"],
  },
  {
    slug: "diversity",
    shortName: "Diversity",
    displayName: "Diversity Essay Scorer",
    description: "The identity or diversity supplemental, asking what you bring to a community.",
    contextForAi: "This is a diversity or identity supplemental. Grade specifically for: avoiding cliches (immigrant story, 'different perspective'), showing specific lived experience over generalized identity talk, and avoiding a self-centered framing of others.",
    typicalWordLimit: "150 to 300 words",
    seoKeywords: ["diversity essay scorer", "identity essay review", "community essay grader"],
  },
  {
    slug: "challenge",
    shortName: "Challenge",
    displayName: "Challenge Essay Scorer",
    description: "The obstacle, setback, or failure essay. Common App #2 and many supplementals.",
    contextForAi: "This is a challenge, obstacle, or failure essay. Grade specifically for: whether the focus stays on response and learning (not the challenge itself), whether the stakes are authentic not inflated, and whether growth is shown through behavior not declared in an epiphany.",
    typicalWordLimit: "250 to 650 words",
    seoKeywords: ["challenge essay scorer", "obstacle essay review", "failure essay grader"],
  },
  {
    slug: "extracurricular",
    shortName: "Extracurricular",
    displayName: "Extracurricular Essay Scorer",
    description: "The elaborate-on-your-activity essay. Harvard, Yale, and other top schools all ask this.",
    contextForAi: "This is an elaborate-on-an-extracurricular essay. Grade specifically for: showing what you actually did (verbs, artifacts, outcomes), revealing character through the activity not claiming it, and avoiding a resume rehash.",
    typicalWordLimit: "150 to 250 words",
    seoKeywords: ["extracurricular essay scorer", "activity essay review", "elaborate on activity grader"],
  },
  {
    slug: "community",
    shortName: "Community",
    displayName: "Community Essay Scorer",
    description: "The community-contribution essay, including MIT's supplemental and many others.",
    contextForAi: "This is a community or contribution essay. Grade specifically for: a clear, specific community (not 'society'), what the student did (not intended), and whether the action respected the community's agency.",
    typicalWordLimit: "200 to 300 words",
    seoKeywords: ["community essay scorer", "contribution essay review", "community supplemental grader"],
  },
  {
    slug: "leadership",
    shortName: "Leadership",
    displayName: "Leadership Essay Scorer",
    description: "Leadership-focused prompts like UC PIQ #1 and many supplementals.",
    contextForAi: "This is a leadership essay. Grade specifically for: showing leadership through a specific moment or decision (not a title), how others were affected, and whether the student took ownership of mistakes and iteration.",
    typicalWordLimit: "250 to 350 words",
    seoKeywords: ["leadership essay scorer", "leadership essay review", "leadership supplemental grader"],
  },
  {
    slug: "creative",
    shortName: "Creative",
    displayName: "Creative Essay Scorer",
    description: "Stanford Short Takes, UChicago quirky prompts, and other creative supplementals.",
    contextForAi: "This is a creative or unusual supplemental. Grade specifically for: answering the literal prompt, revealing something real about the student underneath the cleverness, and not prioritizing wit over substance.",
    typicalWordLimit: "50 to 300 words",
    seoKeywords: ["creative essay scorer", "stanford short takes review", "uchicago essay grader"],
  },
  {
    slug: "extracurricular-activity-150",
    shortName: "150-Char Activity",
    displayName: "Common App Activity Description Scorer (150 chars)",
    description: "The Common App activities section, where each entry is capped at 150 characters.",
    contextForAi: "This is a Common App activity description (strict 150-character limit). Grade specifically for: strong past-tense verbs, concrete numbers (people, hours, dollars), no filler words, and character count compliance. Penalize heavily if over 150 characters.",
    typicalWordLimit: "150 characters",
    seoKeywords: ["common app activity scorer", "150 character activity review", "activity description grader"],
  },
  {
    slug: "additional-info",
    shortName: "Additional Info",
    displayName: "Common App Additional Information Scorer",
    description: "The optional 650-word Additional Information section used to explain context, clarify disruptions, or share what didn't fit elsewhere.",
    contextForAi: "This is the Common App Additional Information section. Grade specifically for: purposeful use (explaining disruption, course context, unusual activities, not just adding more material), absence of resume rehash, and respectful use of the reader's attention.",
    typicalWordLimit: "up to 650 words",
    seoKeywords: ["additional info essay scorer", "common app additional information review", "additional info section grader"],
  },
  {
    slug: "scholarship",
    shortName: "Scholarship",
    displayName: "Scholarship Essay Scorer",
    description: "Merit and need-based scholarship essays, often with specific service or leadership criteria.",
    contextForAi: "This is a scholarship essay. Grade specifically for: directly answering the scholarship criteria (not a general personal statement), concrete evidence of qualities the scholarship names (leadership, service, impact), and a match between the applicant's story and the scholarship's stated mission.",
    typicalWordLimit: "250 to 500 words",
    seoKeywords: ["scholarship essay scorer", "scholarship essay review", "scholarship essay grader"],
  },
  {
    slug: "honors-program",
    shortName: "Honors Program",
    displayName: "Honors Program Essay Scorer",
    description: "University Honors College or program essays, where intellectual engagement is the main thing being tested.",
    contextForAi: "This is an Honors Program application essay. Grade specifically for: intellectual engagement visible in the writing (not declared), willingness to pursue questions without obvious answers, and evidence the applicant would thrive in a seminar setting with curious peers.",
    typicalWordLimit: "250 to 500 words",
    seoKeywords: ["honors program essay scorer", "honors college essay review", "university honors essay"],
  },
  {
    slug: "summer-program",
    shortName: "Summer Program",
    displayName: "Summer Program Essay Scorer",
    description: "Essays for selective summer programs: RSI, TASP, Yale Young Global Scholars, PROMYS, and similar competitive intensives.",
    contextForAi: "This is a selective summer program application essay (RSI, TASP, YYGS, PROMYS, etc.). Grade specifically for: demonstrated intellectual fit with the program, specificity about what the applicant will bring to the cohort, and evidence of prior independent work in the subject. Different summer programs have wildly different cultures (RSI is STEM research, TASP is discussion-based humanities); weight the rubric toward the program implied by the content.",
    typicalWordLimit: "250 to 1000 words (varies by program)",
    seoKeywords: ["summer program essay scorer", "rsi essay review", "tasp essay scorer", "yygs essay"],
  },
  {
    slug: "transfer",
    shortName: "Transfer",
    displayName: "Transfer Essay Scorer",
    description: "Transfer application essays asking why you're moving and what you'll do at the new school.",
    contextForAi: "This is a transfer application essay. Grade specifically for: a clear reason for transferring (without trashing the current school), specific knowledge of the target school, demonstrated growth during time at current school, and a forward-looking frame (what you'll do once admitted).",
    typicalWordLimit: "250 to 650 words",
    seoKeywords: ["transfer essay scorer", "transfer application essay review", "college transfer essay grader"],
  },
  {
    slug: "waitlist-letter",
    shortName: "Waitlist Letter",
    displayName: "Waitlist Letter (Letter of Continued Interest) Scorer",
    description: "Letters of continued interest (LOCI) sent to schools after being waitlisted.",
    contextForAi: "This is a letter of continued interest (LOCI) after being waitlisted. Grade specifically for: a clear commitment to attend if admitted (if that's true), updates on achievements since applying, specific new reasons for the school that have emerged, and brevity (LOCIs work best at 400 words or under). Penalize groveling, generic reaffirmations, and anything that sounds template-driven.",
    typicalWordLimit: "300 to 500 words",
    seoKeywords: ["letter of continued interest", "loci essay scorer", "waitlist letter review"],
  },
  {
    slug: "research-program",
    shortName: "Research Program",
    displayName: "Research Program Essay Scorer",
    description: "Essays for undergraduate research programs: university-sponsored research, NSF REU, Bass Connections, Lab Bridge, etc.",
    contextForAi: "This is a research program application essay. Grade specifically for: a specific research question (not just 'an interest in X'), evidence of prior exposure to research methods, and fit with a specific faculty member or lab mentioned in the application. Rigor of technical framing matters; generic 'I love science' essays should score low.",
    typicalWordLimit: "500 to 1000 words",
    seoKeywords: ["research program essay scorer", "reu essay review", "undergraduate research application"],
  },
  {
    slug: "video-supplement",
    shortName: "Video Supplement",
    displayName: "Video Supplement Script Scorer",
    description: "Scripts or narrative outlines for video essay supplements (Georgetown SFS, Brown, Tufts, and others that invite optional video).",
    contextForAi: "This is a script or narrative outline for a video supplement. Grade specifically for: how it plays as speech (not prose), a distinct on-camera voice, use of the medium (does a video add something the written essays couldn't?), and brevity. Most video supplements are 1 to 2 minutes (roughly 150 to 250 words of spoken content).",
    typicalWordLimit: "150 to 300 words of spoken content",
    seoKeywords: ["video supplement scorer", "video essay college review", "video essay script"],
  },
  {
    slug: "stem-major-why",
    shortName: "STEM Why-Major",
    displayName: "STEM Why-Major Essay Scorer",
    description: "Why-Major essays for STEM applicants (CS, engineering, math, physics, bio, chem).",
    contextForAi: "This is a Why-Major essay for a STEM major. Grade specifically for: evidence of actual engagement with the field (a specific project, question, or paper, not just 'I love science'), intellectual seriousness calibrated for an admissions reader, and specificity about what sub-field excites you. Penalize generic 'I have always loved math' openers.",
    typicalWordLimit: "150 to 400 words",
    seoKeywords: ["stem essay scorer", "why computer science essay", "engineering why-major essay scorer"],
  },
  {
    slug: "business-major-why",
    shortName: "Business Why-Major",
    displayName: "Business Why-Major Essay Scorer",
    description: "Why-Major essays for business applicants (Wharton, McIntire, Ross, Stern, Kelley, Leeds, etc.).",
    contextForAi: "This is a Why-Major essay for business or economics. Grade specifically for: evidence of business curiosity beyond 'I want to be successful' (a specific industry, problem, or research area), concrete exposure to business (club, internship, family business, independent venture), and fit with the target school's specific business school culture.",
    typicalWordLimit: "200 to 500 words",
    seoKeywords: ["business essay scorer", "why wharton essay scorer", "business major essay review"],
  },
  {
    slug: "pre-med-why",
    shortName: "Pre-Med Why-Major",
    displayName: "Pre-Med Why-Major Essay Scorer",
    description: "Essays about wanting to pursue medicine at the undergraduate level.",
    contextForAi: "This is a pre-med intent essay (typically part of an undergraduate application or a BS/MD program essay). Grade specifically for: avoiding the generic 'I want to help people' opener, evidence of genuine clinical or research exposure (shadowing, research, family context, volunteering with real specificity), and maturity about the long medicine pathway. Penalize TV-medicine references.",
    typicalWordLimit: "250 to 500 words",
    seoKeywords: ["pre-med essay scorer", "why medicine essay", "bs md essay review"],
  },
  {
    slug: "arts-portfolio-statement",
    shortName: "Arts Portfolio Statement",
    displayName: "Arts Portfolio Statement Scorer",
    description: "Artist statements or portfolio reflections submitted with arts supplements (visual art, music, theater, film).",
    contextForAi: "This is an arts portfolio statement or artist statement. Grade specifically for: a clear artistic point of view (what the work is actually about), specific references to the student's own work, and evidence of engagement with the art form's traditions. Penalize generic 'art is my passion' openers.",
    typicalWordLimit: "150 to 500 words",
    seoKeywords: ["arts portfolio statement scorer", "artist statement review", "arts supplement essay"],
  },
  {
    slug: "short-answer",
    shortName: "Short Answer",
    displayName: "Short Answer Essay Scorer",
    description: "Supplemental prompts under 150 words, where every line must earn its place.",
    contextForAi: "This is a short supplemental answer (under 150 words). Grade specifically for: a single clear point, no throat-clearing, and a last line that resonates.",
    typicalWordLimit: "50 to 150 words",
    seoKeywords: ["short answer essay scorer", "short supplemental review", "short essay grader"],
  },
  {
    slug: "uchicago-extended-essay",
    shortName: "UChicago Extended",
    displayName: "UChicago Extended Essay Scorer",
    description: "UChicago's famously quirky extended essay, where prompts like 'Find X' or 'Cayley's theorem of ethics' invite risk, wit, and intellectual play.",
    contextForAi: "This is a UChicago extended essay (one of the school's long, intentionally odd supplemental prompts). Grade specifically for: taking the prompt's strangeness seriously, committing to a weird premise rather than hedging, and using the oddity to reveal intellectual character. Penalize safe, templated responses and generic 'I love learning' openers. UChicago rewards essays that would make sense nowhere else.",
    typicalWordLimit: "650 to 1000 words (no strict limit)",
    seoKeywords: ["uchicago extended essay scorer", "uchicago essay review", "uchicago supplemental grader"],
  },
  {
    slug: "disciplinary-explanation",
    shortName: "Disciplinary Explanation",
    displayName: "Disciplinary Incident Explanation Scorer",
    description: "The short explanation many applications require for suspensions, academic integrity incidents, or other disciplinary matters.",
    contextForAi: "This is a disciplinary incident explanation. Grade specifically for: ownership without over-apologizing, specificity about what happened and what the student learned, and evidence of behavioral change since. Penalize excuse-making, blaming others, and minimizing. Brevity is a virtue here.",
    typicalWordLimit: "150 to 400 words",
    seoKeywords: ["disciplinary explanation college essay", "suspension college application essay", "academic integrity incident essay"],
  },
  {
    slug: "oxford-personal-statement",
    shortName: "Oxford / UK Personal Statement",
    displayName: "Oxford and UK Personal Statement Scorer",
    description: "UCAS personal statement for Oxford, Cambridge, and other UK universities - a subject-focused academic statement unlike the US personal essay.",
    contextForAi: "This is a UCAS personal statement (Oxford, Cambridge, Imperial, LSE, etc.). Unlike the US personal essay, UK statements are almost entirely academic - they evaluate the applicant's engagement with their chosen subject. Grade specifically for: at least 70 percent of content being subject-related (not extracurricular), evidence of reading and thinking beyond the A-level syllabus, specificity of academic interest rather than 'I love history', and minimal personal autobiography. Penalize emotional personal storytelling that doesn't tie to academic purpose.",
    typicalWordLimit: "4000 characters (about 600 words)",
    seoKeywords: ["oxford personal statement scorer", "ucas personal statement review", "cambridge personal statement grader", "uk personal statement checker"],
  },
  {
    slug: "yale-short-takes",
    shortName: "Yale Short Takes",
    displayName: "Yale Short Takes Scorer",
    description: "Yale's rapid-fire short-answer supplement: 35-word responses to quick questions about what you're thinking about.",
    contextForAi: "This is a Yale Short Takes response (35 words or fewer per answer). Grade specifically for: strict word-count compliance, a single clear image or claim per answer, and voice density - every word has to earn its place. Penalize hedging, setup, and generic answers. These work best when they're surprising, specific, and would sound weird coming from anyone else.",
    typicalWordLimit: "35 words per answer",
    seoKeywords: ["yale short takes scorer", "yale 35 word essay review", "yale supplemental short answer grader"],
  },
  {
    slug: "mit-short-answers",
    shortName: "MIT Short Answers",
    displayName: "MIT Short Answer Supplement Scorer",
    description: "MIT's supplement: five short-answer prompts about pleasure, community, challenge, and contribution, each capped around 100 to 200 words.",
    contextForAi: "This is an MIT short-answer supplemental (pleasure, community, challenge, contribution, or department fit). Each response is typically 100 to 200 words. Grade specifically for: a single concrete scene or example per answer (not list-mode), evidence of hands-on making or collaborative technical work where relevant, and MIT's unofficial rubric: weird specificity, genuine collaborative instincts, and active verbs. Penalize resume rehash, corporate language, and the 'my passion for STEM' opener.",
    typicalWordLimit: "100 to 200 words per answer",
    seoKeywords: ["mit short answer scorer", "mit supplement review", "mit essay grader", "mit pleasure essay scorer"],
  },
  {
    slug: "questbridge-biographical-essay",
    shortName: "QuestBridge Biographical",
    displayName: "QuestBridge Biographical Essay Scorer",
    description: "QuestBridge National College Match biographical essay, where selective full scholarships hinge on the applicant's personal narrative.",
    contextForAi: "This is a QuestBridge biographical essay (up to 800 words). The QuestBridge reader is specifically looking for how the applicant's context has shaped them. Grade specifically for: concrete details about the applicant's life circumstances (without performing hardship), reflection that connects context to present goals, and evidence of the academic drive that makes the full-scholarship match worth the investment. Avoid generic hardship narratives and essays that ignore the applicant's context entirely.",
    typicalWordLimit: "up to 800 words",
    seoKeywords: ["questbridge biographical essay scorer", "questbridge essay review", "national college match essay grader"],
  },
  {
    slug: "coalition-app-essay",
    shortName: "Coalition App",
    displayName: "Coalition Application Essay Scorer",
    description: "Coalition Application personal essay - similar to the Common App but used by a different subset of schools.",
    contextForAi: "This is a Coalition Application personal essay. Prompts rotate annually but target the same kind of self-revelation as the Common App. Grade specifically for: a clear answer to the chosen prompt, concrete scenes over summary, and voice distinctiveness. Coalition schools weigh these essays similarly to Common App - rubric is essentially the same.",
    typicalWordLimit: "500 to 650 words",
    seoKeywords: ["coalition app essay scorer", "coalition application essay review", "coalition essay grader"],
  },
  {
    slug: "gates-scholarship-essay",
    shortName: "Gates Scholarship",
    displayName: "Gates Scholarship Essay Scorer",
    description: "Gates Scholarship essays - a highly selective full-ride scholarship for minority students with demonstrated leadership and academic excellence.",
    contextForAi: "This is a Gates Scholarship application essay. The Gates Scholarship seeks leaders who have demonstrated service, academic excellence, and community impact. Grade specifically for: clear leadership evidence (not just titles), how the applicant has acted on service or community values, and whether their goals align with the scholarship's mission of developing leaders. Avoid generic 'I want to give back' essays and unsupported leadership claims.",
    typicalWordLimit: "250 to 500 words",
    seoKeywords: ["gates scholarship essay scorer", "gates scholarship essay review", "gates millennium essay grader"],
  },
  {
    slug: "bs-md-program-essay",
    shortName: "BS/MD Program",
    displayName: "BS/MD Program Essay Scorer",
    description: "Essays for combined bachelor's and medical degree programs (Brown PLME, REMS, HPME, and similar).",
    contextForAi: "This is a BS/MD program application essay. These programs commit the student to medicine at age 18, so the bar for demonstrated exposure is higher than a standard pre-med essay. Grade specifically for: significant clinical or research exposure (shadowing alone is not enough), evidence of maturity about a 7- to 8-year committed track, and an understanding of what a physician actually does (beyond 'helping people'). Penalize heavily generic openers and any hint that the applicant hasn't spent real time in medical settings.",
    typicalWordLimit: "500 to 750 words",
    seoKeywords: ["bs md essay scorer", "plme essay review", "direct medical program essay grader"],
  },
  {
    slug: "jack-kent-cooke-scholarship-essay",
    shortName: "Jack Kent Cooke",
    displayName: "Jack Kent Cooke Scholarship Essay Scorer",
    description: "Jack Kent Cooke Foundation scholarship essays - highly selective awards for high-achieving students with financial need.",
    contextForAi: "This is a Jack Kent Cooke Foundation scholarship essay (College or Young Scholars program). The foundation emphasizes academic achievement alongside financial need and leadership. Grade specifically for: concrete evidence of exceptional academic drive, authentic engagement with financial circumstances without performing hardship, and a clear sense of how the scholarship would unlock something the student couldn't otherwise reach.",
    typicalWordLimit: "500 to 1000 words",
    seoKeywords: ["jack kent cooke essay scorer", "jkcf essay review", "jack kent cooke scholarship essay grader"],
  },
  {
    slug: "posse-scholarship-essay",
    shortName: "Posse Scholarship",
    displayName: "Posse Scholarship Essay Scorer",
    description: "Posse Foundation scholarship essays - leadership-focused awards that send multicultural student cohorts to partner colleges.",
    contextForAi: "This is a Posse Foundation scholarship essay. The Posse model sends student cohorts (posses) to partner colleges, selected for leadership potential and ability to thrive in multicultural teams. Grade specifically for: evidence of real leadership in diverse groups (not just titles), demonstrated self-awareness and willingness to grow, and the specific qualities that would make the student a strong member of a tight-knit cohort. Avoid generic 'I'm a leader' claims and overly individualistic framing.",
    typicalWordLimit: "300 to 500 words",
    seoKeywords: ["posse scholarship essay scorer", "posse foundation essay review", "posse essay grader"],
  },
  {
    slug: "common-black-college-application-essay",
    shortName: "Common Black College App",
    displayName: "Common Black College Application Essay Scorer",
    description: "Common Black College Application essay, used to apply to multiple HBCUs with a single application.",
    contextForAi: "This is a Common Black College Application essay. The CBCA allows students to apply to 60+ HBCUs with a single essay. Grade specifically for: clear articulation of why the student is pursuing their intended major, evidence of community engagement, and authentic reflection on how attending an HBCU connects to the student's goals. Avoid generic 'I want to make a difference' openers and essays that could have been written for any college.",
    typicalWordLimit: "500 to 750 words",
    seoKeywords: ["common black college application essay", "cbca essay scorer", "hbcu essay review", "hbcu application essay grader"],
  },
];

export function getEssayType(slug: string): EssayType | undefined {
  return essayTypes.find((t) => t.slug === slug);
}
