export interface EssayPrompt {
  slug: string;
  shortName: string;
  displayName: string;
  fullPrompt: string;
  family: "Common App" | "UC PIQ" | "Supplemental Type";
  wordLimit: number;
  seoKeywords: string[];
}

export const prompts: EssayPrompt[] = [
  {
    slug: "common-app-1-background",
    shortName: "Common App #1",
    displayName: "Common App Prompt #1: Background, Identity, Interest, or Talent",
    fullPrompt: "Some students have a background, identity, interest, or talent that is so meaningful they believe their application would be incomplete without it. If this sounds like you, then please share your story.",
    family: "Common App",
    wordLimit: 650,
    seoKeywords: ["common app prompt 1 examples", "common app background essay", "common app identity essay hook"],
  },
  {
    slug: "common-app-2-obstacle",
    shortName: "Common App #2",
    displayName: "Common App Prompt #2: Lessons from Obstacles",
    fullPrompt: "The lessons we take from obstacles we encounter can be fundamental to later success. Recount a time when you faced a challenge, setback, or failure. How did it affect you, and what did you learn from the experience?",
    family: "Common App",
    wordLimit: 650,
    seoKeywords: ["common app prompt 2", "common app obstacle essay", "common app challenge essay hook"],
  },
  {
    slug: "common-app-3-questioned-idea",
    shortName: "Common App #3",
    displayName: "Common App Prompt #3: Questioned or Challenged a Belief",
    fullPrompt: "Reflect on a time when you questioned or challenged a belief or idea. What prompted your thinking? What was the outcome?",
    family: "Common App",
    wordLimit: 650,
    seoKeywords: ["common app prompt 3", "common app belief essay", "common app questioned idea hook"],
  },
  {
    slug: "common-app-4-gratitude",
    shortName: "Common App #4",
    displayName: "Common App Prompt #4: Gratitude",
    fullPrompt: "Reflect on something that someone has done for you that has made you happy or thankful in a surprising way. How has this gratitude affected or motivated you?",
    family: "Common App",
    wordLimit: 650,
    seoKeywords: ["common app prompt 4", "common app gratitude essay", "common app thankful essay hook"],
  },
  {
    slug: "common-app-5-accomplishment",
    shortName: "Common App #5",
    displayName: "Common App Prompt #5: Accomplishment or Realization",
    fullPrompt: "Discuss an accomplishment, event, or realization that sparked a period of personal growth and a new understanding of yourself or others.",
    family: "Common App",
    wordLimit: 650,
    seoKeywords: ["common app prompt 5", "common app accomplishment essay", "common app growth essay hook"],
  },
  {
    slug: "common-app-6-topic-you-love",
    shortName: "Common App #6",
    displayName: "Common App Prompt #6: A Topic You Lose Track of Time Over",
    fullPrompt: "Describe a topic, idea, or concept you find so engaging that it makes you lose all track of time. Why does it captivate you? What or who do you turn to when you want to learn more?",
    family: "Common App",
    wordLimit: 650,
    seoKeywords: ["common app prompt 6", "common app topic you love", "common app passion essay hook"],
  },
  {
    slug: "common-app-7-your-choice",
    shortName: "Common App #7",
    displayName: "Common App Prompt #7: Topic of Your Choice",
    fullPrompt: "Share an essay on any topic of your choice. It can be one you've already written, one that responds to a different prompt, or one of your own design.",
    family: "Common App",
    wordLimit: 650,
    seoKeywords: ["common app prompt 7", "common app your choice essay", "common app open prompt hook"],
  },
  {
    slug: "uc-piq-leadership",
    shortName: "UC PIQ: Leadership",
    displayName: "UC Personal Insight Question: Leadership",
    fullPrompt: "Describe an example of your leadership experience in which you have positively influenced others, helped resolve disputes, or contributed to group efforts over time.",
    family: "UC PIQ",
    wordLimit: 350,
    seoKeywords: ["uc piq leadership", "uc essay leadership hook", "uc personal insight leadership"],
  },
  {
    slug: "uc-piq-creative-side",
    shortName: "UC PIQ: Creative Side",
    displayName: "UC Personal Insight Question: Creative Side",
    fullPrompt: "Every person has a creative side, and it can be expressed in many ways: problem solving, original and innovative thinking, and artistically, to name a few. Describe how you express your creative side.",
    family: "UC PIQ",
    wordLimit: 350,
    seoKeywords: ["uc piq creative side", "uc essay creativity", "uc personal insight creative"],
  },
  {
    slug: "uc-piq-greatest-talent",
    shortName: "UC PIQ: Greatest Talent",
    displayName: "UC Personal Insight Question: Greatest Talent or Skill",
    fullPrompt: "What would you say is your greatest talent or skill? How have you developed and demonstrated that talent over time?",
    family: "UC PIQ",
    wordLimit: 350,
    seoKeywords: ["uc piq greatest talent", "uc essay skill", "uc personal insight talent"],
  },
  {
    slug: "uc-piq-educational-opportunity",
    shortName: "UC PIQ: Educational Opportunity",
    displayName: "UC Personal Insight Question: Educational Opportunity",
    fullPrompt: "Describe the most significant challenge you have faced and the steps you have taken to overcome this challenge. How has this challenge affected your academic achievement?",
    family: "UC PIQ",
    wordLimit: 350,
    seoKeywords: ["uc piq educational opportunity", "uc essay challenge", "uc personal insight education"],
  },
  {
    slug: "uc-piq-favorite-subject",
    shortName: "UC PIQ: Favorite Subject",
    displayName: "UC Personal Insight Question: Favorite Academic Subject",
    fullPrompt: "Describe your favorite academic subject and explain how it has influenced you.",
    family: "UC PIQ",
    wordLimit: 350,
    seoKeywords: ["uc piq favorite subject", "uc essay academic subject", "uc personal insight subject"],
  },
  {
    slug: "uc-piq-community",
    shortName: "UC PIQ: Community",
    displayName: "UC Personal Insight Question: Community",
    fullPrompt: "What have you done to make your school or your community a better place?",
    family: "UC PIQ",
    wordLimit: 350,
    seoKeywords: ["uc piq community", "uc essay community service", "uc personal insight community"],
  },
  {
    slug: "uc-piq-what-makes-you-unique",
    shortName: "UC PIQ: What Makes You Unique",
    displayName: "UC Personal Insight Question: What Makes You a Strong Candidate",
    fullPrompt: "Beyond what has already been shared in your application, what do you believe makes you stand out as a strong candidate for admissions to the University of California?",
    family: "UC PIQ",
    wordLimit: 350,
    seoKeywords: ["uc piq unique", "uc essay what makes you", "uc personal insight candidate"],
  },
  {
    slug: "uc-piq-challenge",
    shortName: "UC PIQ: Challenge",
    displayName: "UC Personal Insight Question: Significant Challenge",
    fullPrompt: "Describe the most significant challenge you have faced and the steps you have taken to overcome this challenge. How has this challenge affected your academic achievement?",
    family: "UC PIQ",
    wordLimit: 350,
    seoKeywords: ["uc piq challenge", "uc personal insight challenge", "uc essay setback"],
  },
  {
    slug: "why-us-supplemental",
    shortName: "Why Us",
    displayName: "Why This College (Why Us) Supplemental Essay",
    fullPrompt: "Why this college? What specific aspects of our academic programs, campus culture, and community appeal to you?",
    family: "Supplemental Type",
    wordLimit: 250,
    seoKeywords: ["why this college essay hook", "why us essay opener", "supplemental why college hook"],
  },
  {
    slug: "why-major-supplemental",
    shortName: "Why Major",
    displayName: "Why This Major Supplemental Essay",
    fullPrompt: "Why do you want to pursue this major? How did you develop your interest and what do you hope to do with it?",
    family: "Supplemental Type",
    wordLimit: 250,
    seoKeywords: ["why this major essay hook", "why major supplemental", "intended major essay opener"],
  },
  {
    slug: "diversity-identity-supplemental",
    shortName: "Diversity / Identity",
    displayName: "Diversity or Identity Supplemental Essay",
    fullPrompt: "Describe the ways in which your background, identity, interests, or experiences will contribute to the diversity of our community.",
    family: "Supplemental Type",
    wordLimit: 250,
    seoKeywords: ["diversity essay hook", "identity essay opener", "community contribution essay hook"],
  },
  {
    slug: "community-contribution-supplemental",
    shortName: "Community",
    displayName: "Community or Contribution Supplemental Essay",
    fullPrompt: "Describe one way you have contributed to a community you belong to. The community can be your family, school, neighborhood, or any other group you consider yourself part of.",
    family: "Supplemental Type",
    wordLimit: 250,
    seoKeywords: ["community essay hook", "contribution essay opener", "supplemental community essay"],
  },
  {
    slug: "extracurricular-supplemental",
    shortName: "Extracurricular",
    displayName: "Extracurricular Activity Supplemental Essay",
    fullPrompt: "Briefly elaborate on one of your extracurricular activities or work experiences. Why does it matter to you?",
    family: "Supplemental Type",
    wordLimit: 150,
    seoKeywords: ["extracurricular essay hook", "activity essay opener", "elaborate on activity hook"],
  },
];

export function getPrompt(slug: string): EssayPrompt | undefined {
  return prompts.find((p) => p.slug === slug);
}
