export interface Rewriter {
  slug: string;
  shortName: string;
  displayName: string;
  seoDescription: string;
  instruction: string;
  kind: "cut" | "expand" | "tighten" | "tone";
  targetWords?: number;
  seoKeywords: string[];
}

export const rewriters: Rewriter[] = [
  {
    slug: "cut-essay-to-150-words",
    shortName: "Cut to 150 words",
    displayName: "Cut My Essay to 150 Words",
    seoDescription: "Free AI tool that tightens your essay to 150 words while preserving your voice, specific details, and emotional core.",
    instruction: "Rewrite the essay so it lands at exactly 150 words or fewer. Preserve the writer's voice, concrete details, and emotional core. Cut adverbs, filler, and redundant setup before touching scene details.",
    kind: "cut",
    targetWords: 150,
    seoKeywords: ["cut essay to 150 words", "shorten college essay", "150 word essay rewriter"],
  },
  {
    slug: "cut-essay-to-250-words",
    shortName: "Cut to 250 words",
    displayName: "Cut My Essay to 250 Words",
    seoDescription: "Free AI tool that tightens your college essay to exactly 250 words for supplemental essays and Why Us responses.",
    instruction: "Rewrite the essay so it lands at exactly 250 words or fewer. Preserve voice, concrete details, and emotional core. Cut filler and generic lines first.",
    kind: "cut",
    targetWords: 250,
    seoKeywords: ["cut essay to 250 words", "shorten to 250 words", "250 word supplemental rewriter"],
  },
  {
    slug: "cut-essay-to-350-words",
    shortName: "Cut to 350 words",
    displayName: "Cut My Essay to 350 Words",
    seoDescription: "Free AI tool that tightens your essay to 350 words for UC personal insight questions and mid-length supplementals.",
    instruction: "Rewrite the essay so it lands at exactly 350 words or fewer. Preserve voice, concrete details, and emotional core. Cut filler first.",
    kind: "cut",
    targetWords: 350,
    seoKeywords: ["cut essay to 350 words", "UC PIQ 350 word rewriter", "350 word essay shortener"],
  },
  {
    slug: "cut-essay-to-500-words",
    shortName: "Cut to 500 words",
    displayName: "Cut My Essay to 500 Words",
    seoDescription: "Free AI tool that tightens your essay to 500 words for supplementals with a 500-word limit.",
    instruction: "Rewrite the essay so it lands at exactly 500 words or fewer. Preserve voice, concrete details, and emotional core.",
    kind: "cut",
    targetWords: 500,
    seoKeywords: ["cut essay to 500 words", "shorten to 500 words", "500 word essay rewriter"],
  },
  {
    slug: "cut-essay-to-650-words",
    shortName: "Cut to 650 words",
    displayName: "Cut My Essay to 650 Words",
    seoDescription: "Free AI tool that tightens your personal statement to the Common App 650-word limit.",
    instruction: "Rewrite the essay so it lands at exactly 650 words or fewer. Preserve voice, concrete details, and emotional core. This is the Common App personal statement limit.",
    kind: "cut",
    targetWords: 650,
    seoKeywords: ["cut essay to 650 words", "common app 650 word rewriter", "personal statement shortener"],
  },
  {
    slug: "expand-essay-to-500-words",
    shortName: "Expand to 500 words",
    displayName: "Expand My Essay to 500 Words",
    seoDescription: "Free AI tool that expands a short draft to 500 words by adding scene, reflection, and concrete detail, not filler.",
    instruction: "Rewrite the essay to reach roughly 500 words. Expand by adding scene detail, reflection, and concrete examples. Do not add generic transitions, filler, or new claims that aren't grounded in the existing draft.",
    kind: "expand",
    targetWords: 500,
    seoKeywords: ["expand essay to 500 words", "lengthen college essay", "500 word essay expander"],
  },
  {
    slug: "expand-essay-to-650-words",
    shortName: "Expand to 650 words",
    displayName: "Expand My Essay to 650 Words",
    seoDescription: "Free AI tool that grows a short draft into a full 650-word Common App personal statement with real scene and reflection.",
    instruction: "Rewrite the essay to reach roughly 650 words. Expand by deepening scene, adding reflection, or drawing out a second beat. Do not add filler, empty transitions, or generic claims.",
    kind: "expand",
    targetWords: 650,
    seoKeywords: ["expand essay to 650 words", "common app essay lengthener", "650 word expander"],
  },
  {
    slug: "tighten-essay-10-percent",
    shortName: "Tighten by 10%",
    displayName: "Tighten My Essay by 10 Percent",
    seoDescription: "Free AI tool that trims 10 percent of your essay length while preserving voice and the strongest lines.",
    instruction: "Rewrite the essay so the word count drops by roughly 10 percent. Cut adverbs, clauses that repeat an earlier idea, and transitional filler. Preserve the best line of each paragraph.",
    kind: "tighten",
    seoKeywords: ["tighten my college essay", "trim essay 10 percent", "shorten essay without losing voice"],
  },
  {
    slug: "make-essay-more-specific",
    shortName: "Make more specific",
    displayName: "Make My Essay More Specific",
    seoDescription: "Free AI tool that rewrites vague essay lines into concrete, specific detail without inventing facts.",
    instruction: "Rewrite the essay to replace vague, telling lines with more concrete detail. Only add specificity the original draft implies. Do not invent new facts, names, or events. Flag any line where the draft is too vague to rewrite and suggest what the student should add.",
    kind: "tone",
    seoKeywords: ["make essay more specific", "essay specificity rewriter", "show don't tell rewriter"],
  },
  {
    slug: "make-essay-more-personal",
    shortName: "Make more personal",
    displayName: "Make My Essay More Personal",
    seoDescription: "Free AI tool that pulls a generic essay toward first-person voice, lived detail, and your real emotional stakes.",
    instruction: "Rewrite the essay to feel more personal. Lean into first-person voice, interior thought, and small sensory detail. Strip out generalized claims about 'the world' or 'people'. Do not fabricate lived experiences. If a line is too generic to rewrite, suggest what the student could add.",
    kind: "tone",
    seoKeywords: ["make essay more personal", "essay voice rewriter", "personal college essay rewriter"],
  },
  {
    slug: "make-essay-more-formal",
    shortName: "Make more formal",
    displayName: "Make My Essay More Formal",
    seoDescription: "Free AI tool that raises the formality of a college essay without making it stiff. Preserves voice, removes slang and filler.",
    instruction: "Rewrite the essay to be more formal in register. Remove slang, casual contractions where they weaken a sentence, and colloquialisms. Do not make it stiff or remove personality entirely. Keep strong verbs. If a passage is intentionally voicey, preserve it.",
    kind: "tone",
    seoKeywords: ["make essay more formal", "formal essay rewriter", "college essay formality"],
  },
  {
    slug: "add-humor-to-essay",
    shortName: "Add humor",
    displayName: "Add Humor to My Essay",
    seoDescription: "Free AI tool that adds subtle, voice-consistent humor to a college essay without undercutting the emotional stakes.",
    instruction: "Rewrite the essay to include subtle humor consistent with the writer's voice. Humor should come from specific, honest observation (not jokes or wordplay). Never undercut a serious emotional moment with a punchline. If the essay's tone is fundamentally serious, add only 1 or 2 small moments of lightness.",
    kind: "tone",
    seoKeywords: ["add humor to college essay", "funny essay rewriter", "college essay humor"],
  },
  {
    slug: "make-essay-more-vivid",
    shortName: "Make more vivid",
    displayName: "Make My Essay More Vivid",
    seoDescription: "Free AI tool that replaces abstract lines with specific sensory detail. Sight, sound, touch, the small stuff that makes a draft memorable.",
    instruction: "Rewrite the essay to be more vivid. Replace abstract or summary lines with sensory detail (what was seen, heard, smelled, felt). Only add detail the original draft implies. Do not invent facts. If the writer's voice is minimal on purpose, preserve the restraint.",
    kind: "tone",
    seoKeywords: ["make essay more vivid", "vivid writing rewriter", "sensory detail essay"],
  },
  {
    slug: "make-essay-more-academic",
    shortName: "Make more academic",
    displayName: "Make My Essay More Academic",
    seoDescription: "Free AI tool that sharpens reasoning and precision in academic-focused essays (Why Major, STEM, intellectual curiosity prompts).",
    instruction: "Rewrite the essay to be more intellectually precise. Replace hand-wavy language with specific claims, name ideas and methods accurately, and favor analytical over emotional framing where appropriate. Do not make it dry. Preserve voice. Do not invent knowledge or citations.",
    kind: "tone",
    seoKeywords: ["make essay more academic", "academic essay rewriter", "intellectual essay rewrite"],
  },
  {
    slug: "add-reflection-to-essay",
    shortName: "Add reflection",
    displayName: "Add Reflection to My Essay",
    seoDescription: "Free AI tool that deepens an essay's reflective layer. Turns 'what happened' into 'what it meant' without cliches.",
    instruction: "Rewrite the essay to strengthen its reflective layer. Add specific reflection on what a moment meant, changed, or revealed. Avoid cliched reflection (realized, learned, grew). Only reflect on what is grounded in the events of the essay. If the draft already has enough reflection, mark it.",
    kind: "tone",
    seoKeywords: ["add reflection to essay", "reflection rewriter", "college essay reflection"],
  },
  {
    slug: "add-dialogue-to-essay",
    shortName: "Add dialogue",
    displayName: "Add Dialogue to My Essay",
    seoDescription: "Free AI tool that threads natural, voice-consistent dialogue into your college essay to replace summary lines with real exchanges.",
    instruction: "Rewrite the essay to add 1 to 2 short dialogue exchanges where the draft currently summarizes a conversation. Dialogue must be short, natural, and consistent with the draft's voice. Do not invent dialogue that contradicts the draft's content. If no dialogue opportunity exists, say so and return the draft with no changes.",
    kind: "tone",
    seoKeywords: ["add dialogue to essay", "essay dialogue rewriter", "college essay dialogue"],
  },
  {
    slug: "simplify-essay-language",
    shortName: "Simplify language",
    displayName: "Simplify My Essay's Language",
    seoDescription: "Free AI tool that replaces unnecessary complexity in your college essay with clearer, more direct language. No dumbing down, just less jargon.",
    instruction: "Rewrite the essay to simplify unnecessarily complex language. Replace SAT-prep vocabulary with clearer equivalents. Break up any sentences longer than 25 words. Preserve voice and specificity. Do not remove genuinely sophisticated ideas, only obscured ones.",
    kind: "tone",
    seoKeywords: ["simplify college essay", "clearer essay language", "essay language rewriter"],
  },
  {
    slug: "add-specific-details-to-essay",
    shortName: "Add specific details",
    displayName: "Add Specific Details to My Essay",
    seoDescription: "Free AI tool that replaces vague lines with concrete, grounded detail by pulling specifics only from what's implied in your draft.",
    instruction: "Rewrite the essay to replace vague or generic lines with concrete detail. Add specificity only where the original draft implies it. Do not invent new facts, events, or experiences. For lines too vague to rewrite, mark them and suggest what the student needs to add themselves.",
    kind: "tone",
    seoKeywords: ["add specific details essay", "specificity rewriter", "concrete details essay"],
  },
  {
    slug: "remove-ai-voice-from-essay",
    shortName: "Remove AI voice",
    displayName: "Remove AI Voice From My Essay",
    seoDescription: "Free AI tool that detects and removes the patterns admissions readers flag as AI-written: boilerplate phrasing, sanitized emotion, and that smoothed-out corporate tone.",
    instruction: "Rewrite the essay to remove patterns characteristic of AI-generated writing. Specifically: replace corporate transitions (furthermore, moreover, in conclusion), remove sanitized hedging (perhaps, it could be argued), break up suspiciously balanced sentence rhythms, and inject tactile specific detail where the prose smooths over reality. Preserve the student's actual voice and factual claims. If passages already sound human, leave them.",
    kind: "tone",
    seoKeywords: ["remove ai voice essay", "humanize ai essay", "ai detection college essay", "college essay ai detector"],
  },
  {
    slug: "add-emotional-stakes-to-essay",
    shortName: "Add emotional stakes",
    displayName: "Add Emotional Stakes to My Essay",
    seoDescription: "Free AI tool that raises emotional stakes in your college essay through specific detail, interior thought, and honest reflection. No melodrama added.",
    instruction: "Rewrite the essay to strengthen emotional stakes where they're currently flat. Add interior thought, honest reflection, and sensory detail that surfaces what's at stake. Never add melodrama, overwrought description, or emotions not already implied by the draft. If a passage should stay restrained for impact, preserve it.",
    kind: "tone",
    seoKeywords: ["add emotion to essay", "emotional stakes essay", "college essay emotion"],
  },
  {
    slug: "rewrite-essay-as-letter",
    shortName: "Rewrite as a letter",
    displayName: "Rewrite My Essay as a Letter",
    seoDescription: "Free AI tool that reframes your college essay as a direct letter to a specific person. Good for supplementals that explicitly ask for letters or for unlocking voice.",
    instruction: "Rewrite the essay in letter form, addressed to a specific recipient implied by the content. Keep the core scenes, voice, and reflection. Add salutation and closing. Do not invent a recipient. If the essay has no clear addressee, use it as an exercise to find one, but preserve the student's voice throughout.",
    kind: "tone",
    seoKeywords: ["rewrite essay as letter", "letter format essay", "college essay letter format"],
  },
  {
    slug: "add-place-specificity-to-essay",
    shortName: "Add place specificity",
    displayName: "Add Place Specificity to My Essay",
    seoDescription: "Free AI tool that grounds your college essay in specific places. Replaces generic settings with concrete rooms, streets, and landscapes.",
    instruction: "Rewrite the essay to ground scenes in specific places. Replace generic locations with concrete rooms, streets, and physical details. Only add specificity the draft implies. Do not invent cities or buildings not already present. For passages that should stay abstract (reflection, interior thought), leave them.",
    kind: "tone",
    seoKeywords: ["add place details essay", "specific setting college essay", "grounded scene rewriter"],
  },
  {
    slug: "make-essay-more-vulnerable",
    shortName: "Make more vulnerable",
    displayName: "Make My Essay More Vulnerable",
    seoDescription: "Free AI tool that deepens honesty in your college essay without tipping into oversharing. Finds where the draft is holding back and gently invites more.",
    instruction: "Rewrite the essay to be more honest and vulnerable where the draft is hedging. Flag lines that feel overly polished or protected and suggest how to deepen them. Never push toward oversharing or trauma reveals the student didn't include. Preserve emotional restraint where it's working.",
    kind: "tone",
    seoKeywords: ["make essay more vulnerable", "honest essay rewriter", "college essay vulnerability"],
  },
  {
    slug: "rewrite-essay-as-vignettes",
    shortName: "Rewrite as vignettes",
    displayName: "Rewrite My Essay as Vignettes",
    seoDescription: "Free AI tool that reshapes your essay into a series of short vignettes or scenes. Good for experimental structure or Stanford-style short prompts.",
    instruction: "Rewrite the essay as a series of 3 to 5 short vignettes or micro-scenes, each grounded in one concrete moment. Each vignette should connect to the essay's core theme but stand alone as a scene. Keep the student's voice. Do not add new events.",
    kind: "tone",
    seoKeywords: ["vignette essay format", "fragmented essay structure", "experimental essay structure"],
  },
  {
    slug: "rewrite-essay-in-present-tense",
    shortName: "Rewrite in present tense",
    displayName: "Rewrite My Essay in Present Tense",
    seoDescription: "Free AI tool that converts a past-tense college essay into present-tense narration. Raises immediacy and urgency without changing meaning.",
    instruction: "Rewrite the essay so all scene beats are in present tense. Keep reflection and thought passages in their original tense unless changing would sound natural. Do not alter facts, content, or reflection substance. Preserve voice.",
    kind: "tone",
    seoKeywords: ["present tense essay", "present tense narrative", "college essay immediacy"],
  },
  {
    slug: "cut-essay-to-tweet-length",
    shortName: "Distill to 280 chars",
    displayName: "Distill My Essay to a Tweet (280 characters)",
    seoDescription: "Free AI tool that compresses your college essay into a 280-character tweet that captures its core. Good for testing whether your essay has a spine.",
    instruction: "Compress the essay into a single message of 280 characters or fewer. This is the 'can you explain it in one tweet' stress test. Keep the essay's core emotion and concrete detail. Output only the tweet and its character count.",
    kind: "cut",
    targetWords: 50,
    seoKeywords: ["essay one sentence distill", "tweet length essay", "essay elevator pitch"],
  },
  {
    slug: "add-surprise-ending-to-essay",
    shortName: "Add surprise ending",
    displayName: "Add a Surprise Ending to My Essay",
    seoDescription: "Free AI tool that reworks your college essay's ending to land a small surprise or unexpected reversal, without cheapening the story.",
    instruction: "Rewrite the essay's ending to land a small surprise or unexpected reversal that is grounded in material from the body. Do not invent new information. The surprise should be a shift in perspective or a reframing, not a plot twist. If no surprise is available from the existing material, mark it and leave the ending.",
    kind: "tone",
    seoKeywords: ["surprise ending essay", "essay unexpected ending", "essay reversal technique"],
  },
  {
    slug: "cut-activity-to-150-chars",
    shortName: "Cut activity to 150 chars",
    displayName: "Cut My Activity Description to 150 Characters",
    seoDescription: "Free AI tool that rewrites a Common App activity description into a strict 150-character line with strong verbs and concrete numbers.",
    instruction: "Rewrite the activity description as a single line at or under 150 characters (including spaces). Use strong past-tense verbs. Include any specific numbers (people served, dollars raised, hours, percent change) from the draft. Drop filler words. Output only the rewritten description and its final character count.",
    kind: "cut",
    seoKeywords: ["150 character activity rewriter", "common app activity shortener", "activity description tightener"],
  },
  {
    slug: "cut-essay-to-100-words",
    shortName: "Cut to 100 words",
    displayName: "Cut My Essay to 100 Words",
    seoDescription: "Free AI tool that tightens your essay to 100 words for ultra-short supplementals like Yale's Why Yale and many short-answer prompts.",
    instruction: "Rewrite the essay so it lands at exactly 100 words or fewer. Preserve voice, concrete details, and emotional core. Cut everything not earning its place.",
    kind: "cut",
    targetWords: 100,
    seoKeywords: ["cut essay to 100 words", "100 word college essay", "yale why yale 100 word rewriter"],
  },
  {
    slug: "cut-essay-to-200-words",
    shortName: "Cut to 200 words",
    displayName: "Cut My Essay to 200 Words",
    seoDescription: "Free AI tool that tightens your essay to exactly 200 words for short supplementals and tight why-major prompts.",
    instruction: "Rewrite the essay so it lands at exactly 200 words or fewer. Preserve voice and concrete details. Cut filler first.",
    kind: "cut",
    targetWords: 200,
    seoKeywords: ["cut essay to 200 words", "200 word essay rewriter", "short supplemental shortener"],
  },
  {
    slug: "cut-essay-to-400-words",
    shortName: "Cut to 400 words",
    displayName: "Cut My Essay to 400 Words",
    seoDescription: "Free AI tool that tightens your college essay to 400 words for many school-specific supplementals at that word limit.",
    instruction: "Rewrite the essay so it lands at exactly 400 words or fewer. Preserve voice, concrete details, and emotional core. Cut filler before touching scene.",
    kind: "cut",
    targetWords: 400,
    seoKeywords: ["cut essay to 400 words", "400 word essay rewriter", "400 word supplemental shortener"],
  },
  {
    slug: "rewrite-essay-opening-in-medias-res",
    shortName: "Rewrite opening in medias res",
    displayName: "Rewrite My Essay's Opening In Medias Res",
    seoDescription: "Free AI tool that rewrites your college essay's first paragraph to drop the reader into the middle of a scene. Kills 'ever since I was young' openers.",
    instruction: "Rewrite only the opening paragraph of the essay so it drops the reader into the middle of a concrete, in-progress scene. Use sensory detail and present action. Preserve the essay's voice and do not alter any facts. If the opening is already in medias res, mark it and return unchanged.",
    kind: "tone",
    seoKeywords: ["in medias res college essay", "rewrite essay opening", "fix essay opener"],
  },
  {
    slug: "add-concrete-numbers-to-essay",
    shortName: "Add concrete numbers",
    displayName: "Add Concrete Numbers to My Essay",
    seoDescription: "Free AI tool that surfaces places in your essay where a specific number would replace vague scale. Flags where the draft needs them but doesn't fabricate figures.",
    instruction: "Identify lines in the essay that reference scale, duration, frequency, or quantity in vague terms ('a lot', 'for a while', 'many people'). Flag each and suggest the kind of specific number the student should add. Do NOT invent numbers the draft doesn't imply. If the draft already uses specific numbers well, say so.",
    kind: "tone",
    seoKeywords: ["add numbers to college essay", "specific details essay numbers", "essay quantify rewriter"],
  },
  {
    slug: "strengthen-essay-closing-line",
    shortName: "Strengthen closing line",
    displayName: "Strengthen My Essay's Closing Line",
    seoDescription: "Free AI tool that rewrites the final sentence of your college essay to land with resonance instead of fading into summary.",
    instruction: "Rewrite only the final sentence of the essay. The new closing should resonate with the essay's core tension and feel earned by the preceding material — not summarize what the reader just read. Do not invent new content. If the current closing already resonates, say so and leave it.",
    kind: "tone",
    seoKeywords: ["strengthen essay closing", "rewrite essay ending", "better essay last line"],
  },
  {
    slug: "fix-essay-transitions",
    shortName: "Fix transitions",
    displayName: "Fix My Essay's Transitions",
    seoDescription: "Free AI tool that smooths or removes weak transitions in your college essay. Kills 'in addition' and 'moreover' and makes paragraph handoffs feel earned.",
    instruction: "Review the essay paragraph by paragraph. Flag every weak or formulaic transition ('in addition', 'moreover', 'furthermore', 'however', 'in conclusion') and rewrite each to hand off organically from the last paragraph's ending to the next paragraph's opening. Preserve voice. Do not add transitions where none are needed.",
    kind: "tone",
    seoKeywords: ["fix essay transitions", "smooth college essay transitions", "essay paragraph transitions rewriter"],
  },
  {
    slug: "rewrite-essay-as-montage",
    shortName: "Rewrite as montage",
    displayName: "Rewrite My Essay as a Montage",
    seoDescription: "Free AI tool that reshapes your college essay as a montage of small, connected moments instead of a single linear narrative.",
    instruction: "Rewrite the essay as a montage of 3 to 5 small moments, each grounded in concrete detail and linked by a single thread (an object, a habit, a recurring feeling). Each moment should stand on its own while contributing to the essay's core theme. Preserve voice. Do not invent new events. If the current essay is already structured as a montage, mark it and leave it.",
    kind: "tone",
    seoKeywords: ["montage college essay", "essay montage structure", "fragmented essay rewriter"],
  },
  {
    slug: "make-essay-less-grandiose",
    shortName: "Make less grandiose",
    displayName: "Make My Essay Less Grandiose",
    seoDescription: "Free AI tool that deflates grand claims in your college essay so the concrete specifics can do the work. Kills 'changed my life forever' energy.",
    instruction: "Rewrite the essay to remove grandiose or over-reaching claims. Flag lines like 'changed my life forever', 'taught me everything I know', 'the most important moment'. Replace them with smaller, more honest, more specific claims. Preserve voice. Do not flatten genuinely big moments — just stop the essay from overselling them.",
    kind: "tone",
    seoKeywords: ["make essay less dramatic", "tone down college essay", "essay grandiose rewriter"],
  },
  {
    slug: "rewrite-essay-with-less-hedging",
    shortName: "Remove hedging",
    displayName: "Rewrite My Essay with Less Hedging",
    seoDescription: "Free AI tool that strips hedging language from your college essay. Kills 'I think', 'maybe', 'kind of', and 'I believe' so your claims land.",
    instruction: "Rewrite the essay to remove hedging and qualifiers that weaken claims. Strip phrases like 'I think', 'maybe', 'sort of', 'I believe', 'it could be argued'. Let declarative statements stand. Preserve honest uncertainty only where it's actually relevant to the essay's content — not where it's just a verbal tic. Preserve voice.",
    kind: "tone",
    seoKeywords: ["remove hedging college essay", "confident college essay rewriter", "stop hedging essay"],
  },
  {
    slug: "cut-filler-from-first-paragraph",
    shortName: "Cut first-paragraph filler",
    displayName: "Cut Filler From My Essay's First Paragraph",
    seoDescription: "Free AI tool that identifies and removes throat-clearing filler from your opening paragraph so your essay starts where it should.",
    instruction: "Focus only on the first paragraph of the essay. Identify and cut any setup, context-establishing sentences, throat-clearing, or throat-clearing that doesn't need to exist. Suggest the sentence where the essay should actually start. Preserve voice. Report the word count saved.",
    kind: "cut",
    seoKeywords: ["cut essay filler", "fix opening paragraph essay", "essay throat clearing rewriter"],
  },
  {
    slug: "remove-cliche-phrases-from-essay",
    shortName: "Remove cliche phrases",
    displayName: "Remove Cliche Phrases From My Essay",
    seoDescription: "Free AI tool that flags and rewrites tired college essay cliches — 'stepped out of my comfort zone', 'passion for learning', 'ever since I was little'.",
    instruction: "Flag every college essay cliche in the draft: 'comfort zone', 'passion for', 'ever since I was young', 'came to realize', 'learned that', 'taught me the importance of'. Rewrite each flagged line to say the same thing in a more specific, less familiar way. If a cliche is being used ironically or subverted, preserve it and mark it as intentional.",
    kind: "tone",
    seoKeywords: ["college essay cliche remover", "cliche phrases college essay", "remove tired phrases essay"],
  },
  {
    slug: "add-physical-sensation-to-essay",
    shortName: "Add physical sensation",
    displayName: "Add Physical Sensation to My Essay",
    seoDescription: "Free AI tool that grounds your college essay in body-level detail. Temperature, texture, weight, breath — the tangible stuff that makes a scene real.",
    instruction: "Rewrite the essay to add physical, body-level sensation (temperature, texture, weight, breath, muscle tension) to scene-based passages. Only add sensation the draft implies. Do not invent facts. Preserve voice. Avoid florid or purple prose; the addition should feel like real noticing, not writerly decoration.",
    kind: "tone",
    seoKeywords: ["add sensation to essay", "physical detail college essay", "body detail essay rewriter"],
  },
  {
    slug: "rewrite-essay-with-shorter-sentences",
    shortName: "Shorter sentences",
    displayName: "Rewrite My Essay With Shorter Sentences",
    seoDescription: "Free AI tool that breaks up long sentences in your college essay. Raises pace and clarity without making the prose choppy.",
    instruction: "Rewrite the essay to shorten sentences that run over 25 words. Break them into two or three tighter sentences. Preserve voice and nuance; don't strip clauses that carry meaning. Keep some longer sentences where the length serves the thought. Report average sentence length before and after.",
    kind: "tone",
    seoKeywords: ["shorter sentences college essay", "break up long sentences essay", "pace college essay rewriter"],
  },
  {
    slug: "rewrite-essay-with-stronger-verbs",
    shortName: "Stronger verbs",
    displayName: "Rewrite My Essay With Stronger Verbs",
    seoDescription: "Free AI tool that replaces weak verbs in your college essay with precise, active ones. Kills 'was', 'is', and 'had' in favor of verbs that actually do work.",
    instruction: "Rewrite the essay to replace weak verbs (forms of 'to be', 'have', 'do', 'get', 'make') with more specific, precise verbs where the context supports it. Do not force verbs that change meaning or sound forced. Preserve voice. Avoid overreaching into florid language — the goal is verbs that do work, not verbs that show off.",
    kind: "tone",
    seoKeywords: ["stronger verbs college essay", "active verbs essay rewriter", "essay verb upgrade"],
  },
  {
    slug: "add-single-central-image-to-essay",
    shortName: "Add central image",
    displayName: "Add a Single Central Image to My Essay",
    seoDescription: "Free AI tool that surfaces a recurring image or object your college essay could anchor around. Strengthens cohesion without rewriting content.",
    instruction: "Read the essay and identify a specific concrete object, place, or image that could anchor the essay as a recurring motif. Suggest where the image should appear (opening, midpoint, closing) and how each reappearance should deepen. Do not invent images not implied by the draft. If the essay already has a strong central image, mark it.",
    kind: "tone",
    seoKeywords: ["central image college essay", "essay motif rewriter", "recurring image essay technique"],
  },
];

export function getRewriter(slug: string): Rewriter | undefined {
  return rewriters.find((r) => r.slug === slug);
}
