export type SchoolCategory =
  | "Ivy League"
  | "Elite Private"
  | "Top Public"
  | "Liberal Arts"
  | "Top Tech / STEM"
  | "Selective Private";

export interface School {
  slug: string;
  name: string;
  shortName: string;
  location: string;
  state: string;
  type: "Private" | "Public";
  category: SchoolCategory;
  knownFor: string;
  whyUsWordLimit?: number;
}

export const schools: School[] = [
  { slug: "harvard", name: "Harvard University", shortName: "Harvard", location: "Cambridge, Massachusetts", state: "Massachusetts", type: "Private", category: "Ivy League", knownFor: "the residential Houses system, the Harvard Yard freshman experience, and cross-school resources across Harvard College, FAS, and the grad schools", whyUsWordLimit: 150 },
  { slug: "yale", name: "Yale University", shortName: "Yale", location: "New Haven, Connecticut", state: "Connecticut", type: "Private", category: "Ivy League", knownFor: "the 14 residential colleges, the Directed Studies program, and Yale's unusually strong arts and theater ecosystem", whyUsWordLimit: 125 },
  { slug: "princeton", name: "Princeton University", shortName: "Princeton", location: "Princeton, New Jersey", state: "New Jersey", type: "Private", category: "Ivy League", knownFor: "its senior thesis requirement, the undergraduate focus, the eating clubs, and the no-loan financial aid policy", whyUsWordLimit: 250 },
  { slug: "stanford", name: "Stanford University", shortName: "Stanford", location: "Stanford, California", state: "California", type: "Private", category: "Elite Private", knownFor: "interdisciplinary research, d.school design thinking, Silicon Valley proximity, and the open undergraduate curriculum", whyUsWordLimit: 100 },
  { slug: "mit", name: "Massachusetts Institute of Technology", shortName: "MIT", location: "Cambridge, Massachusetts", state: "Massachusetts", type: "Private", category: "Top Tech / STEM", knownFor: "hands-on UROP research, the hack culture, IAP independent activities period, and deep interdisciplinary engineering", whyUsWordLimit: 250 },
  { slug: "columbia", name: "Columbia University", shortName: "Columbia", location: "New York, New York", state: "New York", type: "Private", category: "Ivy League", knownFor: "the Core Curriculum, its location in Manhattan, and cross-registration with Barnard and Juilliard", whyUsWordLimit: 150 },
  { slug: "upenn", name: "University of Pennsylvania", shortName: "Penn", location: "Philadelphia, Pennsylvania", state: "Pennsylvania", type: "Private", category: "Ivy League", knownFor: "the One University Policy that lets undergrads take classes across Wharton, Engineering, Nursing, and the College", whyUsWordLimit: 200 },
  { slug: "cornell", name: "Cornell University", shortName: "Cornell", location: "Ithaca, New York", state: "New York", type: "Private", category: "Ivy League", knownFor: "seven distinct undergraduate colleges, its agricultural and hotel school legacies, and the 'any person, any study' motto", whyUsWordLimit: 650 },
  { slug: "brown", name: "Brown University", shortName: "Brown", location: "Providence, Rhode Island", state: "Rhode Island", type: "Private", category: "Ivy League", knownFor: "the Open Curriculum, S/NC grade option, and the PLME and Brown-RISD dual degree programs", whyUsWordLimit: 200 },
  { slug: "dartmouth", name: "Dartmouth College", shortName: "Dartmouth", location: "Hanover, New Hampshire", state: "New Hampshire", type: "Private", category: "Ivy League", knownFor: "the D-Plan quarter system, the rural setting, the first-year seminars, and outdoorsy culture", whyUsWordLimit: 100 },
  { slug: "duke", name: "Duke University", shortName: "Duke", location: "Durham, North Carolina", state: "North Carolina", type: "Private", category: "Elite Private", knownFor: "Trinity College and Pratt Engineering, DukeEngage, and the tight undergraduate community", whyUsWordLimit: 250 },
  { slug: "northwestern", name: "Northwestern University", shortName: "Northwestern", location: "Evanston, Illinois", state: "Illinois", type: "Private", category: "Elite Private", knownFor: "the quarter system, the Medill School of Journalism, and interdisciplinary programs like MMSS and ISP", whyUsWordLimit: 300 },
  { slug: "johns-hopkins", name: "Johns Hopkins University", shortName: "Johns Hopkins", location: "Baltimore, Maryland", state: "Maryland", type: "Private", category: "Elite Private", knownFor: "its world-leading biomedical research, the Applied Physics Lab, and deep opportunities in public health" },
  { slug: "chicago", name: "University of Chicago", shortName: "UChicago", location: "Chicago, Illinois", state: "Illinois", type: "Private", category: "Elite Private", knownFor: "the Core, the life of the mind culture, and its quirky supplemental essay prompts", whyUsWordLimit: 650 },
  { slug: "caltech", name: "California Institute of Technology", shortName: "Caltech", location: "Pasadena, California", state: "California", type: "Private", category: "Top Tech / STEM", knownFor: "its tiny class sizes, the Honor Code, JPL, and the deepest undergraduate research culture in STEM" },
  { slug: "rice", name: "Rice University", shortName: "Rice", location: "Houston, Texas", state: "Texas", type: "Private", category: "Elite Private", knownFor: "the residential college system, the small undergraduate size, and the Texas Medical Center proximity", whyUsWordLimit: 150 },
  { slug: "vanderbilt", name: "Vanderbilt University", shortName: "Vanderbilt", location: "Nashville, Tennessee", state: "Tennessee", type: "Private", category: "Elite Private", knownFor: "the residential colleges on The Martha Rivers Ingram Commons, Immersion Vanderbilt, and Nashville music scene", whyUsWordLimit: 400 },
  { slug: "notre-dame", name: "University of Notre Dame", shortName: "Notre Dame", location: "Notre Dame, Indiana", state: "Indiana", type: "Private", category: "Elite Private", knownFor: "Catholic intellectual tradition, residence halls that function like houses, and a deeply loyal alumni network" },
  { slug: "emory", name: "Emory University", shortName: "Emory", location: "Atlanta, Georgia", state: "Georgia", type: "Private", category: "Elite Private", knownFor: "the Emory and Oxford College campuses, strong pre-health pathways, and its public health ties to the CDC" },
  { slug: "wustl", name: "Washington University in St. Louis", shortName: "WashU", location: "St. Louis, Missouri", state: "Missouri", type: "Private", category: "Elite Private", knownFor: "flexibility to pursue multiple majors across schools, strong medical and design programs, and a collaborative, low-ego culture" },
  { slug: "georgetown", name: "Georgetown University", shortName: "Georgetown", location: "Washington, D.C.", state: "District of Columbia", type: "Private", category: "Elite Private", knownFor: "the School of Foreign Service, cura personalis, and internship access in D.C." },
  { slug: "carnegie-mellon", name: "Carnegie Mellon University", shortName: "CMU", location: "Pittsburgh, Pennsylvania", state: "Pennsylvania", type: "Private", category: "Top Tech / STEM", knownFor: "the School of Computer Science, the College of Fine Arts, and unusual interdisciplinary programs like BXA and BHA" },
  { slug: "usc", name: "University of Southern California", shortName: "USC", location: "Los Angeles, California", state: "California", type: "Private", category: "Elite Private", knownFor: "the Iovine and Young Academy, Annenberg, SCA film school, and the Los Angeles network" },
  { slug: "tufts", name: "Tufts University", shortName: "Tufts", location: "Medford, Massachusetts", state: "Massachusetts", type: "Private", category: "Selective Private", knownFor: "the Fletcher School ties, ExCollege student-taught courses, and quirky supplemental essays" },
  { slug: "nyu", name: "New York University", shortName: "NYU", location: "New York, New York", state: "New York", type: "Private", category: "Elite Private", knownFor: "the Tisch School of the Arts, Stern, Gallatin's self-designed major, and its globally distributed campuses" },
  { slug: "boston-college", name: "Boston College", shortName: "Boston College", location: "Chestnut Hill, Massachusetts", state: "Massachusetts", type: "Private", category: "Selective Private", knownFor: "its Jesuit mission, the Core, and the Carroll School of Management undergraduate experience" },
  { slug: "boston-university", name: "Boston University", shortName: "BU", location: "Boston, Massachusetts", state: "Massachusetts", type: "Private", category: "Selective Private", knownFor: "the Kilachand Honors College, the College of Communication, and access to Boston's research ecosystem" },
  { slug: "northeastern", name: "Northeastern University", shortName: "Northeastern", location: "Boston, Massachusetts", state: "Massachusetts", type: "Private", category: "Selective Private", knownFor: "the co-op program that embeds students in industry for multiple semesters" },
  { slug: "tulane", name: "Tulane University", shortName: "Tulane", location: "New Orleans, Louisiana", state: "Louisiana", type: "Private", category: "Selective Private", knownFor: "its public service graduation requirement, strong pre-law and pre-med tracks, and New Orleans culture" },
  { slug: "wake-forest", name: "Wake Forest University", shortName: "Wake Forest", location: "Winston-Salem, North Carolina", state: "North Carolina", type: "Private", category: "Selective Private", knownFor: "small class sizes, Pro Humanitate mission, and a test-optional tradition that predates the trend" },
  { slug: "lehigh", name: "Lehigh University", shortName: "Lehigh", location: "Bethlehem, Pennsylvania", state: "Pennsylvania", type: "Private", category: "Selective Private", knownFor: "integrated business and engineering programs, IBE and CSB dual degrees, and an unusually tight alumni network" },
  { slug: "case-western", name: "Case Western Reserve University", shortName: "Case Western", location: "Cleveland, Ohio", state: "Ohio", type: "Private", category: "Selective Private", knownFor: "its SAGES program, cooperative research, and deep biomedical pipelines through the Cleveland Clinic" },
  { slug: "amherst", name: "Amherst College", shortName: "Amherst", location: "Amherst, Massachusetts", state: "Massachusetts", type: "Private", category: "Liberal Arts", knownFor: "the open curriculum, the Five College Consortium, and a tradition of small seminar teaching" },
  { slug: "williams", name: "Williams College", shortName: "Williams", location: "Williamstown, Massachusetts", state: "Massachusetts", type: "Private", category: "Liberal Arts", knownFor: "tutorials that replicate Oxford-style two-student seminars, the winter study term, and a rural setting" },
  { slug: "pomona", name: "Pomona College", shortName: "Pomona", location: "Claremont, California", state: "California", type: "Private", category: "Liberal Arts", knownFor: "the Claremont Consortium, cross-registration with Pitzer, Scripps, Harvey Mudd, and CMC, and its tight residential culture" },
  { slug: "swarthmore", name: "Swarthmore College", shortName: "Swarthmore", location: "Swarthmore, Pennsylvania", state: "Pennsylvania", type: "Private", category: "Liberal Arts", knownFor: "the Honors program modeled on Oxford tutorials, Quaker values, and the tri-college consortium" },
  { slug: "bowdoin", name: "Bowdoin College", shortName: "Bowdoin", location: "Brunswick, Maine", state: "Maine", type: "Private", category: "Liberal Arts", knownFor: "the Common Good tradition, the coastal Maine campus, and rigorous small-class teaching" },
  { slug: "middlebury", name: "Middlebury College", shortName: "Middlebury", location: "Middlebury, Vermont", state: "Vermont", type: "Private", category: "Liberal Arts", knownFor: "its language schools, environmental studies strengths, and the J-term winter study period" },
  { slug: "wesleyan", name: "Wesleyan University", shortName: "Wesleyan", location: "Middletown, Connecticut", state: "Connecticut", type: "Private", category: "Liberal Arts", knownFor: "the College of Social Studies, its film studies reputation, and its politically engaged student body" },
  { slug: "carleton", name: "Carleton College", shortName: "Carleton", location: "Northfield, Minnesota", state: "Minnesota", type: "Private", category: "Liberal Arts", knownFor: "the trimester system, strong STEM within a liberal arts setting, and the Arb natural area" },
  { slug: "grinnell", name: "Grinnell College", shortName: "Grinnell", location: "Grinnell, Iowa", state: "Iowa", type: "Private", category: "Liberal Arts", knownFor: "its open curriculum with a single first-year tutorial, and a deep student-led culture of self-governance" },
  { slug: "colby", name: "Colby College", shortName: "Colby", location: "Waterville, Maine", state: "Maine", type: "Private", category: "Liberal Arts", knownFor: "Jan Plan month-long term, strong environmental science, and the DavisConnects experiential-learning program" },
  { slug: "bates", name: "Bates College", shortName: "Bates", location: "Lewiston, Maine", state: "Maine", type: "Private", category: "Liberal Arts", knownFor: "its Short Term May program, the senior thesis requirement, and a long test-optional history" },
  { slug: "hamilton", name: "Hamilton College", shortName: "Hamilton", location: "Clinton, New York", state: "New York", type: "Private", category: "Liberal Arts", knownFor: "its open curriculum, writing-intensive tradition, and tight alumni mentorship program" },
  { slug: "davidson", name: "Davidson College", shortName: "Davidson", location: "Davidson, North Carolina", state: "North Carolina", type: "Private", category: "Liberal Arts", knownFor: "its Honor Code, small class sizes, and Division I athletic tradition inside a liberal arts college" },
  { slug: "claremont-mckenna", name: "Claremont McKenna College", shortName: "CMC", location: "Claremont, California", state: "California", type: "Private", category: "Liberal Arts", knownFor: "the research institutes, strong PPE and government programs, and cross-registration across the 5Cs" },
  { slug: "harvey-mudd", name: "Harvey Mudd College", shortName: "Harvey Mudd", location: "Claremont, California", state: "California", type: "Private", category: "Top Tech / STEM", knownFor: "the Common Core, its required humanities and social sciences for STEM majors, and the Clinic Program" },
  { slug: "barnard", name: "Barnard College", shortName: "Barnard", location: "New York, New York", state: "New York", type: "Private", category: "Liberal Arts", knownFor: "its partnership with Columbia, the Foundations curriculum, and an all-women's undergraduate college in Manhattan" },
  { slug: "smith", name: "Smith College", shortName: "Smith", location: "Northampton, Massachusetts", state: "Massachusetts", type: "Private", category: "Liberal Arts", knownFor: "its Five College Consortium access, engineering within a women's college, and the house residential system" },
  { slug: "wellesley", name: "Wellesley College", shortName: "Wellesley", location: "Wellesley, Massachusetts", state: "Massachusetts", type: "Private", category: "Liberal Arts", knownFor: "cross-registration with MIT, its women's college tradition, and the Wellesley W network" },
  { slug: "vassar", name: "Vassar College", shortName: "Vassar", location: "Poughkeepsie, New York", state: "New York", type: "Private", category: "Liberal Arts", knownFor: "the open curriculum, its multidisciplinary programs, and a strong film and drama tradition" },
  { slug: "haverford", name: "Haverford College", shortName: "Haverford", location: "Haverford, Pennsylvania", state: "Pennsylvania", type: "Private", category: "Liberal Arts", knownFor: "its student-run Honor Code, the Quaker tradition, and the Bi-Co and Tri-Co consortia with Bryn Mawr and Swarthmore" },
  { slug: "berkeley", name: "University of California, Berkeley", shortName: "UC Berkeley", location: "Berkeley, California", state: "California", type: "Public", category: "Top Public", knownFor: "its public research scale, DeCal courses, and the Haas and College of Engineering reputations" },
  { slug: "ucla", name: "University of California, Los Angeles", shortName: "UCLA", location: "Los Angeles, California", state: "California", type: "Public", category: "Top Public", knownFor: "its scale and breadth, strong film and medical schools, and LA location" },
  { slug: "ucsd", name: "University of California, San Diego", shortName: "UC San Diego", location: "La Jolla, California", state: "California", type: "Public", category: "Top Public", knownFor: "its seven undergraduate colleges, Scripps oceanography, and its biomedical research ecosystem" },
  { slug: "michigan", name: "University of Michigan, Ann Arbor", shortName: "Michigan", location: "Ann Arbor, Michigan", state: "Michigan", type: "Public", category: "Top Public", knownFor: "the Ross, Ford, Taubman, and engineering schools, the Michigan Learning Communities, and the Leaders and Best culture" },
  { slug: "unc", name: "University of North Carolina at Chapel Hill", shortName: "UNC", location: "Chapel Hill, North Carolina", state: "North Carolina", type: "Public", category: "Top Public", knownFor: "Carolina Covenant, strong public policy and journalism, and the Research Triangle context" },
  { slug: "uva", name: "University of Virginia", shortName: "UVA", location: "Charlottesville, Virginia", state: "Virginia", type: "Public", category: "Top Public", knownFor: "the Jeffersonian Academical Village, the Honor Code, and strong humanities programming" },
  { slug: "uiuc", name: "University of Illinois Urbana-Champaign", shortName: "Illinois", location: "Champaign, Illinois", state: "Illinois", type: "Public", category: "Top Public", knownFor: "the Grainger College of Engineering, Gies Business, and its big Big Ten research campus" },
  { slug: "wisconsin", name: "University of Wisconsin, Madison", shortName: "Wisconsin", location: "Madison, Wisconsin", state: "Wisconsin", type: "Public", category: "Top Public", knownFor: "the Wisconsin Idea, its strong research output, and a huge range of First-Year Interest Groups" },
  { slug: "washington", name: "University of Washington", shortName: "UW", location: "Seattle, Washington", state: "Washington", type: "Public", category: "Top Public", knownFor: "the Paul G. Allen School of Computer Science and its Seattle research and tech pipelines" },
  { slug: "georgia-tech", name: "Georgia Institute of Technology", shortName: "Georgia Tech", location: "Atlanta, Georgia", state: "Georgia", type: "Public", category: "Top Tech / STEM", knownFor: "its cooperative education program, strong engineering and computing, and the Create-X startup ecosystem" },
  { slug: "purdue", name: "Purdue University", shortName: "Purdue", location: "West Lafayette, Indiana", state: "Indiana", type: "Public", category: "Top Public", knownFor: "the Krannert School of Management, strong aviation and engineering, and its Giant Leaps research focus" },
  { slug: "texas-austin", name: "University of Texas at Austin", shortName: "UT Austin", location: "Austin, Texas", state: "Texas", type: "Public", category: "Top Public", knownFor: "the McCombs School of Business, Cockrell Engineering, Plan II, and Austin's tech scene" },
  { slug: "florida", name: "University of Florida", shortName: "Florida", location: "Gainesville, Florida", state: "Florida", type: "Public", category: "Top Public", knownFor: "its Honors Program, Heavener School of Business, and strong public research output" },
  { slug: "ohio-state", name: "Ohio State University", shortName: "Ohio State", location: "Columbus, Ohio", state: "Ohio", type: "Public", category: "Top Public", knownFor: "Fisher College of Business, strong engineering and medical pipelines, and a flagship Big Ten campus" },
  { slug: "penn-state", name: "Pennsylvania State University", shortName: "Penn State", location: "University Park, Pennsylvania", state: "Pennsylvania", type: "Public", category: "Top Public", knownFor: "the Schreyer Honors College, Smeal business school, and a multi-campus structure for transferring majors" },
  { slug: "maryland", name: "University of Maryland, College Park", shortName: "Maryland", location: "College Park, Maryland", state: "Maryland", type: "Public", category: "Top Public", knownFor: "the Honors College, strong computer science and public policy, and the D.C. metro access" },
  { slug: "rutgers", name: "Rutgers University, New Brunswick", shortName: "Rutgers", location: "New Brunswick, New Jersey", state: "New Jersey", type: "Public", category: "Top Public", knownFor: "its undergraduate schools structure and the SAS Honors Program" },
  { slug: "minnesota", name: "University of Minnesota, Twin Cities", shortName: "Minnesota", location: "Minneapolis, Minnesota", state: "Minnesota", type: "Public", category: "Top Public", knownFor: "its seven freshman colleges, Carlson business school, and twin cities research partnerships" },
  { slug: "pittsburgh", name: "University of Pittsburgh", shortName: "Pitt", location: "Pittsburgh, Pennsylvania", state: "Pennsylvania", type: "Public", category: "Top Public", knownFor: "UPMC-driven pre-health pipelines, its tight connection with Carnegie Mellon, and the university honors college" },
  { slug: "virginia-tech", name: "Virginia Tech", shortName: "Virginia Tech", location: "Blacksburg, Virginia", state: "Virginia", type: "Public", category: "Top Public", knownFor: "Ut Prosim service mission, strong engineering and agriculture, and corps of cadets tradition" },
  { slug: "stony-brook", name: "Stony Brook University", shortName: "Stony Brook", location: "Stony Brook, New York", state: "New York", type: "Public", category: "Top Public", knownFor: "its Simons Center ties, strong physics and math, and the SUNY honors pipeline" },
  { slug: "binghamton", name: "Binghamton University", shortName: "Binghamton", location: "Vestal, New York", state: "New York", type: "Public", category: "Top Public", knownFor: "its value-for-money reputation among SUNY schools and the Harpur Fellows program" },
  { slug: "baylor", name: "Baylor University", shortName: "Baylor", location: "Waco, Texas", state: "Texas", type: "Private", category: "Selective Private", knownFor: "its Christian intellectual tradition, the Honors College, and a strong pre-med pipeline" },
  { slug: "miami", name: "University of Miami", shortName: "Miami", location: "Coral Gables, Florida", state: "Florida", type: "Private", category: "Selective Private", knownFor: "the Frost School of Music, marine science ties, and the Foote Fellows honors program" },
  { slug: "smu", name: "Southern Methodist University", shortName: "SMU", location: "Dallas, Texas", state: "Texas", type: "Private", category: "Selective Private", knownFor: "its Cox business school, Meadows arts program, and the Hilltop residential commons system" },
  { slug: "gwu", name: "George Washington University", shortName: "GW", location: "Washington, D.C.", state: "District of Columbia", type: "Private", category: "Selective Private", knownFor: "the Elliott School of International Affairs, D.C. internship access, and the Corcoran arts program" },
  { slug: "american", name: "American University", shortName: "American", location: "Washington, D.C.", state: "District of Columbia", type: "Private", category: "Selective Private", knownFor: "its School of International Service and close ties to D.C. policy and journalism" },
  { slug: "bucknell", name: "Bucknell University", shortName: "Bucknell", location: "Lewisburg, Pennsylvania", state: "Pennsylvania", type: "Private", category: "Liberal Arts", knownFor: "its College of Management within a liberal arts setting, strong engineering, and a residential college program" },
  { slug: "colgate", name: "Colgate University", shortName: "Colgate", location: "Hamilton, New York", state: "New York", type: "Private", category: "Liberal Arts", knownFor: "Core Distinction courses, extended study-abroad programs, and the Maroon Council advising model" },
  { slug: "richmond", name: "University of Richmond", shortName: "Richmond", location: "Richmond, Virginia", state: "Virginia", type: "Private", category: "Liberal Arts", knownFor: "the Robins School of Business, its unique coordinate college tradition, and the Jepson School of Leadership Studies" },
];

export function getSchool(slug: string): School | undefined {
  return schools.find((s) => s.slug === slug);
}

export const schoolSlugs = schools.map((s) => s.slug);
